"""Translation taken from mypv websetup version 222.04"""

my_pv_trans = {
    "language_code": ["de", "en", "fr", "es"],
    "footer": [
        "&copy; 2020 my-PV GmbH, Österreich.<br>Alle Rechte vorbehalten.<br><a href='http://www.my-pv.com'>www.my-pv.com</a>",
        "&copy; 2020 my-PV GmbH, Austria.<br>All Rights reserved.<br><a href='http://www.my-pv.com'>www.my-pv.com</a>",
        "&copy; 2020 my-PV GmbH, Autriche.<br>Tous droits réservés.<br><a href='http://www.my-pv.com'>www.my-pv.com</a>",
        "&copy; 2020 my-PV GmbH, Austria.<br>Todos los derechos reservados.<br><a href='http://www.my-pv.com'>www.my-pv.com</a>",
    ],
    "header": ["Kopfzeile", "header", "En-tête", "Cabecera"],
    "device": ["Gerät", "Device", "Dispositif", "Dispositivo"],
    "dev_search": [
        "Geräte suchen",
        "Search devices",
        "Recherche de dispositifs",
        "Búsqueda de dispositivos",
    ],
    "ip_range": [
        "IP Suchbereich",
        "IP Search Range",
        "Plage de recherche IP",
        "Rango de búsqueda de IP",
    ],
    "submit": ["Übernehmen", "Submit", "Soumettre", "Presentar"],
    "chart_text": [
        "Für die grafische Darstellung der Betriebsdaten muss my-PV.LIVE verwendet werden. Siehe dazu:",
        "For the the graphical representation of the operating data, my-PV.LIVE must be used - see:",
        "Pour la représentation graphique des données de fonctionnement, il faut utiliser my-PV.LIVE. Voir également:",
        "Para la representación gráfica de los datos de funcionamiento se debe utilizar mi-PV.LIVE. Ver también:",
    ],
    "alert_nodevice": [
        "Mit keinem Gerät verbunden - bitte ein Gerät auswählen bzw. neue Geräte suchen.",
        "Not connected to any device - please select a device or search for new devices.",
        "Non connecté à un appareil - veuillez sélectionner un appareil ou rechercher de nouveaux appareils.",
        "No está conectado a ningún dispositivo - por favor, seleccione un dispositivo o busque nuevos dispositivos.",
    ],
    "alert_reboot": [
        "Bitte warten bis Geräteneustart durchgeführt wurde.",
        "Please wait while rebooting device.",
        "Veuillez attendre que le dispositif ait redémarré.",
        "Por favor, espere hasta que el dispositivo se haya reiniciado.",
    ],
    "alert_factory_reset": [
        "Bitte warten bis Gerät auf Werkseinstellung zurückgesetzt ist.",
        "Please wait until factory reset is done.",
        "Veuillez attendre que le dispositif soit réinitialisé aux réglages d'usine.",
        "Por favor, espere hasta que el dispositivo se haya reajustado a la configuración de fábrica.",
    ],
    "alert_fwupdate": [
        "Bitte warten bis Software-Update am Gerät durchgeführt ist.",
        "Please wait while firmware update is performed.",
        "Veuillez attendre que la mise à jour du logiciel ait été effectuée sur le dispositif.",
        "Por favor, espere hasta que la actualización del software se haya llevado a cabo en el dispositivo.",
    ],
    "alert_download": [
        "Es ist ein Update des my-PV Websetups verfügbar! Update downloaden unter: ",
        "There is an update for your my-PV Websetup available! Download update at: ",
        "Une mise à jour de votre my-PV Websetup est disponible! Téléchargez la mise à jour sous: ",
        "¡Hay una actualización para su my-PV Websetup disponible! Descarga la actualización en: ",
    ],
    "alert_read_ip_blocked": [
        "Ihr Browser unterstützt eine automatische Suche nach my-PV Geräten leider nicht.",
        "Your browser does not support an automatic scan for my-PV devices.",
        "Votre navigateur ne prend pas en charge la recherche automatique de dispositifs my-PV",
        "Su navegador no soporta una búsqueda automática de dispositivos de mi PC",
    ],
    "alert_read_ip_blocked_chrome": [
        'Um die automatische Suche nach my-PV Geräten zu ermöglichen, müssen Sie unter chrome://flags/#enable-webrtc-hide-local-ips-with-mdns die Einstellung "Anonymize local IPs exposed by WebRTC." auf "Disabled" umstellen.',
        'To enable the automatic search for my-PV devices, you have to change the setting "Anonymize local IPs exposed by WebRTC." to "Disabled" under chrome://flags/#enable-webrtc-hide-local-ips-with-mdns',
        'Pour activer la recherche automatique de dispositifs my-PV, vous devez régler le paramètre "Anonymize local IPs exposed by WebRTC." en "Disabled" sous chrome://flags/#enable-webrtc-hide-local-ips-with-mdns.',
        'Para habilitar la búsqueda automática de dispositivos de mi VP, debes cambiar el ajuste "Anonymize local IPs exposed by WebRTC." a "Disabled" bajo chrome://flags/#enable-webrtc-hide-local-ips-with-mdns',
    ],
    "alert_change_eth_mode": [
        "Führen Sie einen Geräte-Reset durch, damit der geänderte Ethernet-Modus (LAN / WLAN) wirksam wird.",
        "Perform a device reset so that the changed Ethernet mode (LAN / WiFi) takes effect.",
        "Effectuez une réinitialisation de l'appareil afin que le mode Ethernet modifié (LAN / WiFi) prenne effet.",
        "Realice un reinicio del dispositivo para que el modo Ethernet cambiado (LAN / WiFi) surta efecto.",
    ],
    "acthor_error1": [
        "Fehler 101: Keine Phase an Relais Mittelkontakt erkannt",
        "Error 101: No phase on relay center contact detected",
        "Erreur 101: Aucune phase sur le relais Contact central détecté",
        "Error 101: No hay fase en el relé Contacto central detectado",
    ],
    "acthor_error2": [
        "Fehler 102: Temperatur Sensor 1 erforderlich für WW Sicherstellung. Prüfen Sie ob der Sensor aktiviert wurde!",
        "Error 102: Temperature sensor 1 required for hotwater boost. Check if the sensor has been activated!",
        "Erreur 102: Capteur de température 1 requis pour Sécurité par fusible WW. Vérifier si le capteur a été activé !",
        "Error 102: Sensor de temperatura 1 necesario para copia de seguridad WW. ¡Compruebe si el sensor ha sido activado!",
    ],
    "acthor_error3": [
        "Fehler 103: Temperatur Sensor 1 erforderlich für diese Betriebsart. Prüfen Sie ob der Sensor aktiviert wurde!",
        "Error 103: Temperature sensor 1 required for this mode. Check if the sensor has been activated!",
        "Erreur 103: Capteur de température 1 requis pour ce mode. Vérifier si le capteur a été activé !",
        "Error 103: Sensor de temperatura 1 necesario para este modo de funcionamiento ¡Compruebe si el sensor ha sido activado!",
    ],
    "acthor_error4": [
        "Fehler 104: Temperatur Sensor 1 erforderlich für Raumheizung. Prüfen Sie ob der Sensor aktiviert wurde!",
        "Error 104: Temperature sensor 1 required for spaceheating. Check if the sensor has been activated!",
        "Erreur 104: Capteur de température 1 requis pour Chauffage des pièces. Vérifier si le capteur a été activé !",
        "Error 104: Sensor de temperatura 1 necesario para la calefacción de la habitación. ¡Compruebe si el sensor ha sido activado!",
    ],
    "acthor_error5": [
        "Fehler 105: Temperatur Sensor 1 erforderlich für Warmwasser. Prüfen Sie ob der Sensor aktiviert wurde!",
        "Error 105: Temperature sensor 1 required for hotwater. Check if the sensor has been activated!",
        "Erreur 105: Capteur de température 1 requis pour Eau chaude. Vérifier si le capteur a été activé !",
        "Error 105: Se requiere el sensor de temperatura 1 para el agua caliente. ¡Compruebe si el sensor ha sido activado!",
    ],
    "acthor_error6": [
        "Fehler 106: Regelbare Leistung < Last an Relais",
        "Error 106: Controllable power < Load at relay",
        "Erreur 106: Puissance réglable < Charge au relais",
        "Error 106: Potencia regulable < Carga en el relé",
    ],
    "acthor_error7": [
        "Fehler 107: Temperatur Sensor 2 erforderlich für Raumheizung. Prüfen Sie ob der Sensor aktiviert wurde!",
        "Error 107: Temperature sensor 2 required for spaceheating. Check if the sensor has been activated!",
        "Erreur 107: Capteur de température 2 requis pour Chauffage des pièces. Vérifier si le capteur a été activé !",
        "Error 107: Sensor de temperatura 2 necesario para la calefacción de la habitación. ¡Compruebe si el sensor ha sido activado!",
    ],
    "acthor_error8": [
        "Fehler 108: Temperatur Sensor 2 erforderlich für PWM. Prüfen Sie ob der Sensor aktiviert wurde!",
        "Error 108: Temperature sensor 2 required for PWM. Check if the sensor has been activated!",
        "Erreur 108: Capteur de température 2 requis pour PWM. Vérifier si le capteur a été activé !",
        "Error 108: Sensor de temperatura 2 necesario para PWM. ¡Compruebe si el sensor ha sido activado!",
    ],
    "acthor_error9": [
        "Fehler 109: Temperatur Sensor 1 erforderlich für Legionellenschutz. Prüfen Sie ob der Sensor aktiviert wurde!",
        "Error 109: Temperature sensor 1 required for legionella protection. Check if the sensor has been activated!",
        "Erreur 109: Capteur de température 1 requis pour Protection contre la légionellose. Vérifier si le capteur a été activé !",
        "Error 109: Sensor de temperatura 1 necesario para la protección contra la legionela. ¡Compruebe si el sensor ha sido activado!",
    ],
    "acthor_error10": [
        "Fehler 110: FW Update misslungen. Kommunikations-Fehler mit Leistungsteil Gerät neu starten",
        "Error 110: FW Update failed. Communication-Error with power stage. Restart device",
        "Erreur 110: Échec de la mise à jour du micrologiciel. Erreur de communication avec la partie d'alimentation Redémarrer l'appareil",
        "Error 110: FW Error de actualización. Error de comunicación con Sección de alimentación Reiniciar dispositivo ",
    ],
    "acthor_error11": [
        "Fehler 111: FW Update misslungen. Problem mit p-File. Gerät ausschalten. SD Karte mit p-File einsetzen. Siehe Anleitung my-pv.com Gerät neu starten",
        "Error 111: FW Update failed. Problem with p-File. Switch off device. Insert SD card with p-File. See manual my-pv.com Restart device",
        "Erreur 111: Échec de la mise à jour du micrologiciel. Problème avec le fichier p. Éteindre l'appareil. Insérer la carte SD avec le fichier p. Voir les instructions sur my-pv.com Redémarrer l'appareil",
        "Error 111: FW Error de actualización. Problema con p-File. Desconectar dispositivo. SD Insertar tarjeta con p-File. Ver instrucciones en my-pv.com Reiniciar dispositivo  ",
    ],
    "acthor_error12": [
        "Fehler 112: Temperatur Sensor 3 erforderlich für WW Sicherstellung. Prüfen Sie ob der Sensor aktiviert wurde!",
        "Error 112: Temperature sensor 3 required for hotwater boost. Check if the sensor has been activated!",
        "Erreur 112: Capteur de température 3 requis pour Sécurité WW. Vérifier si le capteur a été activé !",
        "Error 112: Sensor de temperatura 3 necesario para copia de seguridad WW. ¡Compruebe si el sensor ha sido activado!",
    ],
    "acthor_error13": [
        "Fehler 113: LT Kommunikation Timeout. Gerät neu starten",
        "Error 113: Power stage communication timeout. Restart device",
        "Erreur 113: Expiration du délai de communication LT. Redémarrer l'appareil",
        "Error 113: LT Límite de tiempo de comunicación. Reiniciar dispositivo",
    ],
    "acthor_error14": [
        "Fehler 114: LT hängt in Bootloader. Gerät neu starten",
        "Error 114: Power stage in boot mode. Restart device",
        "Erreur 114: LT bloqué dans le Bootloader. Redémarrer l'appareil",
        "Error 114: LT se cuelga en el Bootloader. Reiniciar dispositivo",
    ],
    "acthor_error15": [
        "Fehler 115: Temperatur Sensoren 2+3 erforderlich für Raumheizung. Prüfen Sie ob die Sensoren aktiviert wurden!",
        "Error 115: Temperature sensors 2+3 required for spaceheating. Check if sensors have been activated!",
        "Erreur 115: Capteurs de température 2+3 requis pour Chauffage des pièces. Vérifier si les capteurs ont été activés !",
        "Error 115: Sensores de temperatura 2+3 necesarios para la calefacción de la habitación. ¡Compruebe si los sensores han sido activados!",
    ],
    "acthor_error16": [
        "Fehler 116: Leistungsteil Überlast. Installation prüfen.",
        "Error 116: Powerstage overload. Check installation",
        "Erreur 116: Partie d'alimentation Surcharge. Vérifier l'installation.",
        "Error 116: Sección de potencia Sobrecarga. Comprobar la instalación.",
    ],
    "acthor_error17": [
        "Fehler 117: Leistungsteil Übertemperatur. Gerät schaltet nach Abkühlung wieder ein.",
        "Error 117: Powerstage overtemperature. Device restarts after cool down.",
        "Erreur 117: PArtie d'alimentation Surchauffe. L'appareil redémarre après le refroidissement.",
        "Error 117: Sección de potencia Sobretemperatura. El dispositivo se enciende de nuevo después de enfriarse.",
    ],
    "chart": ["Charts", "Charts", "Graphiques", "Gráficos"],
    "chart_m3_warning": [
        "Wir an der geschalteten Last kein my-PV Meter zur Leistungsmessungverwendet, so kann die Leistungsanzeige des ACTHORs und die Energieaufzeichnung des Datenloggers diesen Verbrauch nicht berücksichtigen!",
        "If no my-PV Meter is used for power measurement at the switched load, the power display of the ACTHOR and the energy recording of the data logger cannot take this consumption into account!",
        "Si aucun my-PV Meter n'est utilisé pour mesurer la puissance à la charge commutée, l'affichage de la puissance de l'ACTHOR et l'enregistrement de l'énergie de l'enregistreur de données ne peuvent pas prendre en compte cette consommation !",
        "Si no se utiliza el my-PV Meter para la medición de la potencia en la carga conmutada, la pantalla de potencia del ACTHOR y el registro de energía del registrador de datos no pueden tener en cuenta este consumo.",
    ],
    "chart_load": [
        "Daten werden geladen - Einen Moment Bitte",
        "Loading - One moment please",
        "Données en cours de chargement - Veuillez patienter",
        "Los datos se están cargando. Un momento, por favor.",
    ],
    "chart_type": ["Chart:", "Chart:", "Graphique:", "Gráfico:"],
    "chart_type0": ["Leistung", "Power", "Puissance", "Potencia"],
    "chart_type1": ["Leistung 1", "Power 1", "Puissance 1", "Potencia 1"],
    "chart_type2": ["Leistung 2", "Power 2", "Puissance 2", "Potencia 2"],
    "chart_type3": ["Leistung 3", "Power 3", "Puissance 3", "Potencia 3"],
    "chart_type4": ["Zähler", "Meter", "Compteur", "Medidor de potencia"],
    "chart_type5": [
        "Temperatur 1+2",
        "Temperature 1+2",
        "Température 1+2",
        "Temperatura 1+2",
    ],
    "chart_type6": [
        "Temperatur 3+4",
        "Temperature 3+4",
        "Température 3+4",
        "Temperatura 3",
    ],
    "chart_timespan": ["Zeitraum:", "Time span:", "Durée:", "Periodo:"],
    "chart_time": ["Datum:", "Date:", "Date:", "Fecha:"],
    "chart_data0_str": [
        "Temperatur 1",
        "Temperature 1",
        "Température 1",
        "Temperatura 1",
    ],
    "chart_data1_str": [
        "Temperatur 2",
        "Temperature 2",
        "Température 2",
        "Temperatura 2",
    ],
    "chart_data2_str": [
        "Temperatur 3",
        "Temperature 3",
        "Température 3",
        "Temperatura 3",
    ],
    "chart_data3_str": [
        "Temperatur 4",
        "Temperature 4",
        "Température 4",
        "Temperatura 4",
    ],
    "chart_data4_meter_str": [
        "Netzbezug",
        "Grid part",
        "Achat réseau",
        "Consumo de la red",
    ],
    "chart_data5_meter_str": [
        "Netzeinspeisung",
        "Feed-in",
        "Injection réseau",
        "Suministro a la red",
    ],
    "chart_data4_power_str": [
        "Solaranteil",
        "Solarpart",
        "Part solaire",
        "Energía solar FV",
    ],
    "chart_data5_power_str": [
        "Netzanteil",
        "Gridpart",
        "Part réseau",
        "Energía de la red",
    ],
    "chart_data4_power1_str": [
        "Solaranteil 1",
        "Solarpart 1",
        "Part solaire 1",
        "Energía solar FV 1",
    ],
    "chart_data5_power1_str": [
        "Netzanteil 1",
        "Gridpart 1",
        "Part réseau 1",
        "Energía de la red 1",
    ],
    "chart_data4_power2_str": [
        "Solaranteil 2",
        "Solarpart 2",
        "Part solaire 2",
        "Energía solar FV 2",
    ],
    "chart_data5_power2_str": [
        "Netzanteil 2",
        "Gridpart 2",
        "Part réseau 2",
        "Energía de la red 2",
    ],
    "chart_data4_power3_str": [
        "Solaranteil 3",
        "Solarpart 3",
        "Part solaire 3",
        "Energía solar FV 3",
    ],
    "chart_data5_power3_str": [
        "Netzanteil 3",
        "Gridpart 3",
        "Part réseau 3",
        "Energía de la red 3",
    ],
    "info": ["Status", "State", "État", "Estado"],
    "info_state": ["Status:", "State:", "État:", "Estado:"],
    "info_state_elwa_1": [
        ", Keine Verbindung",
        ", No communication",
        ", Pas de connexion",
        ", No hay conexión",
    ],
    "info_state_elwa_2": [", Heizen", ", Heating", ", Chauffage", ", Calentamiento"],
    "info_state_elwa_3": [", Standby", ", Standby", ", Standby", ", Standby"],
    "info_state_elwa_4": [
        ", Heizen Sicherstellung",
        ", Boost heating",
        ", Sécurisation chauffage",
        ", Boost calentamiento",
    ],
    "info_state_elwa_5": [
        ", Heizen beendet",
        ", Heating finished",
        ", Chauffage terminé",
        ", El calentamiento se acabó",
    ],
    "info_state_elwa_9": [
        ", Setup Modus",
        ", Setup mode",
        ", Mode configuration",
        ", Modo de configuración",
    ],
    "info_state_elwa_20": [
        ", Heizen Legionellenschutz",
        ", Legionella boost",
        ", Protection anti-légionellose chauffage",
        ", Protección contra la legionela calentamiento",
    ],
    "info_state_elwa_21": [
        ", Gerät deaktiviert",
        ", Device disabled",
        ", Dispositif désactivé",
        ", Dispositivo desactivado",
    ],
    "info_state_elwa_22": [
        ", Sperrzeit aktiv",
        ", Device blocked",
        ", Blocage activé",
        ", Tiempo de parada activo",
    ],
    "info_state_elwa_201": [
        ", Fehler Übertemperatursicherung",
        ", Overtemp fuse error",
        ", Erreur fusible surchauffe",
        ", Error protección de sobrecalentamiento",
    ],
    "info_state_elwa_202": [
        ", Fehler Übertemperatur",
        ", Overtemp error",
        ", Erreur surchauffe",
        ", Error sobretemperatura",
    ],
    "info_state_elwa_203": [
        ", Fehler Gerätetemperatur",
        ", Device overheat error",
        ", Erreur température dispositif",
        ", error temperatura dispositivo",
    ],
    "info_state_elwa_204": [
        ", Fehler Hardware",
        ", Hardware error",
        ", Erreur matériel",
        ", Error hardware",
    ],
    "info_state_elwa_205": [
        ", Fehler Temperaturfühler",
        ", Temp sensor error",
        ", Erreur capteur de température",
        ", Error sensor temperatura",
    ],
    "info_state_elwa_209": [
        ", Fehler Mainboard",
        ", Mainboard error",
        ", Erreur de la carte mère",
        ", Error de la placa base",
    ],
    "info_state_acthor_0": [", Standby", ", Standby", ", Standby", ", Standby"],
    "info_state_acthor_1": [", Heizen", ", Heating", ", Chauffage", ", Calentamiento"],
    "info_state_acthor_2": [
        ", Heizen Sicherstellung",
        ", Boost heating",
        ", Sécurisation chauffage",
        ", Boost calentamiento",
    ],
    "info_state_acthor_3": [
        ", Heizen beendet",
        ", Heating finished",
        ", Chauffage terminé",
        ", El calentamiento se acabó",
    ],
    "info_state_acthor_4": [
        ", Keine Verbindung / Deaktiviert",
        ", No communication / Deactivated",
        ", Pas de connexion / Désactivé",
        ", No hay conexión / Desactivado",
    ],
    "info_state_acthor_5": [", Fehler", ", Error", ", Erreur", ", Error"],
    "info_state_acthor_6": [
        ", Sperrzeit aktiv",
        ", Device blocked",
        ", Blocage activé",
        ", Tiempo de parada activo",
    ],
    "info_state_acthor9s_0": [", Standby", ", Standby", ", Standby", ", Standby"],
    "info_state_acthor9s_1": [
        ", Heizen",
        ", Heating",
        ", Chauffage",
        ", Calentamiento",
    ],
    "info_state_acthor9s_2": [
        ", Heizen Sicherstellung",
        ", Boost heating",
        ", Sécurisation chauffage",
        ", Boost calentamiento",
    ],
    "info_state_acthor9s_3": [
        ", Heizen beendet",
        ", Heating finished",
        ", Chauffage terminé",
        "El calentamiento se acabó",
    ],
    "info_state_acthor9s_4": [
        ", Keine Verbindung",
        ", No communication",
        ", Pas de connexion",
        ", No hay conexión",
    ],
    "info_state_acthor9s_5": [", Fehler", ", Error", ", Erreur", ", Error"],
    "info_state_acthor9s_6": [
        ", Sperrzeit aktiv",
        ", Device blocked",
        ", Blocage activé",
        ", Tiempo de parada activo",
    ],
    "info_state_elwa2_0": [", Standby", ", Standby", ", Standby", ", Standby"],
    "info_state_elwa2_1": [", Heizen", ", Heating", ", Chauffage", ", Calentamiento"],
    "info_state_elwa2_2": [
        ", Heizen Sicherstellung",
        ", Boost heating",
        ", Sécurisation chauffage",
        ", Boost calentamiento",
    ],
    "info_state_elwa2_3": [
        ", Heizen beendet",
        ", Heating finished",
        ", Chauffage terminé",
        ", El calentamiento se acabó",
    ],
    "info_state_elwa2_4": [
        ", Keine Verbindung / Deaktiviert",
        ", No communication / Deactivated",
        ", Pas de connexion / Désactivé",
        ", No hay conexión / Desactivado",
    ],
    "info_state_elwa2_5": [", Fehler", ", Error", ", Erreur", ", Error"],
    "info_state_elwa2_6": [
        ", Sperrzeit aktiv",
        ", Device blocked",
        ", Blocage activé",
        ", Tiempo de parada activo",
    ],
    "info_power_elwa": ["AC ELWA-E:", "AC ELWA-E:", "AC ELWA-E:", "AC ELWA-E:"],
    "info_power_elwa2": ["AC ELWA-2:", "AC ELWA-2:", "AC ELWA-2:", "AC ELWA-2:"],
    "info_power_acthor": ["ACTHOR:", "ACTHOR:", "ACTHOR:", "ACTHOR:"],
    "info_power_acthor9s": ["ACTHOR9s:", "ACTHOR9s:", "ACTHOR9s:", "ACTHOR9s:"],
    "info_bstpower": [
        "Warmwassersicherstellung:",
        "Boost:",
        "Sécurisation eau chaude:",
        "Calentamiento auxiliar:",
    ],
    "info_power_solar": ["Solaranteil:", "Solarpart:", "Part solaire:", "Cuota solar:"],
    "info_power_grid": ["Netzanteil:", "Gridpart:", "Part réseau:", "Cuota red:"],
    "info_power1_solar": [
        "Ausgang 1 Solaranteil:",
        "Output 1 Solarpart:",
        "Sortie 1 Part solaire:",
        "Salida 1 cuota solar:",
    ],
    "info_power1_grid": [
        "Ausgang 1 Netzanteil:",
        "Output 1 Gridpart:",
        "Sortie 1 Part réseau:",
        "Salida 1 cuota red:",
    ],
    "info_power2_solar": [
        "Ausgang 2 Solaranteil:",
        "Output 2 Solarpart:",
        "Sortie 2 Part solaire:",
        "Salida 2 cuota solar:",
    ],
    "info_power2_grid": [
        "Ausgang 2 Netzanteil:",
        "Output 2 Gridpart:",
        "Sortie 2 Part réseau:",
        "Salida 2 cuota red:",
    ],
    "info_power3_solar": [
        "Ausgang 3 Solaranteil:",
        "Output 3 Solarpart:",
        "Sortie 3 Part solaire:",
        "Salida 3 cuota solar:",
    ],
    "info_power3_grid": [
        "Ausgang 3 Netzanteil:",
        "Output 3 Gridpart:",
        "Sortie 3 Part réseau:",
        "Salida 3 cuota red:",
    ],
    "info_load_state": ["Last:", "Load:", "Charge:", "Carga:"],
    "info_load_nom": [
        "Nominelle Leistung Last:",
        "Load nominal power:",
        "Puissance nominale charge:",
        "Carga de potencia nominal:",
    ],
    "info_rel1_out": [
        "Relais Status:",
        "Relays state:",
        "État relais:",
        "Estado del relé:",
    ],
    "info_watertemp": [
        "Wassertemperatur:",
        "Watertemperature:",
        "Température eau",
        "Temperatura del agua:",
    ],
    "info_temp1": [
        "Temperatur 1:",
        "Temperature 1:",
        "Température 1:",
        "Temperatura 1:",
    ],
    "info_temp2": [
        "Temperatur 2:",
        "Temperature 2:",
        "Température 2:",
        "Temperatura 2:",
    ],
    "info_temp3": [
        "Temperatur 3:",
        "Temperature 3:",
        "Température 3:",
        "Temperatura 3:",
    ],
    "info_temp4": [
        "Temperatur 4:",
        "Temperature 4:",
        "Température 4:",
        "Temperatura 4:",
    ],
    "info_targettemp": [
        "Zieltemperatur:",
        "Targettemperature:",
        "Température cible:",
        "Temperatura objetivo:",
    ],
    "info_boostact": ["Boost aktiv:", "Boost active:", "Boost actif:", "Boost activo:"],
    "info_booststate": [
        "WW Sicherstellung Status:",
        "HW Boost state:",
        "État sécurisation eau chaude:",
        "Estado boost agua caliente:",
    ],
    "info_legboostnext": [
        "Nächster Legionellen-Boost:",
        "Next legionella boost:",
        "Prochain boost anti-légionellose:",
        "Próximo boost anti-legionela:",
    ],
    "info_legboostnext_days": ["Tage", "days", "Jours", "Días"],
    "info_date": ["Datum:", "Date:", "Date:", "Fecha:"],
    "info_time": ["Zeit:", "Time:", "Heure:", "Hora:"],
    "info_pump_pwm": ["Pumpe PWM:", "Pump PWM:", "Pompes PWM:", "PWM de la bomba:"],
    "info_control_state": [
        "Status Ansteuerung:",
        "Control state:",
        "État de commande:",
        "Estado de control:",
    ],
    "info_blockact": [
        "Block aktiv:",
        "Block active:",
        "Bloc actif:",
        "Bloqueo activo:",
    ],
    "info_blockstate": [
        "Block Status:",
        "Block State:",
        "État bloc:",
        "Estado de bloqueo:",
    ],
    "info_meter1_id": [
        "gefundener my-PV Meter 1 ID:",
        "discovered my-PV Meter 1 ID:",
        "ID my-PV Meter 1 trouvé:",
        "my-PV Meter 1 ID encontrado:",
    ],
    "info_meter1_ip": [
        "gefundener my-PV Meter 1 IP:",
        "discovered my-PV Meter 1 IP:",
        "IP my-PV Meter 1 trouvé:",
        "my-PV Meter 1 IP encontrado:",
    ],
    "info_meter2_id": [
        "gefundener my-PV Meter 2 ID:",
        "discovered my-PV Meter 2 ID:",
        "ID my-PV Meter 2 trouvé:",
        "my-PV Meter 2 ID encontrado:",
    ],
    "info_meter2_ip": [
        "gefundener my-PV Meter 2 IP:",
        "discovered my-PV Meter 2 IP:",
        "IP my-PV Meter 2 trouvé:",
        "my-PV Meter 2 IP encontrado:",
    ],
    "info_meter3_id": [
        "gefundener my-PV Meter 3 ID:",
        "discovered my-PV Meter 3 ID:",
        "ID my-PV Meter 3 trouvé:",
        "my-PV Meter 3 ID encontrado:",
    ],
    "info_meter3_ip": [
        "gefundener my-PV Meter 3 IP:",
        "discovered my-PV Meter 3 IP:",
        "IP my-PV Meter 3 trouvé:",
        "my-PV Meter 3 IP encontrado:",
    ],
    "info_meter4_id": [
        "gefundener my-PV Meter 4 ID:",
        "discovered my-PV Meter 4 ID:",
        "ID my-PV Meter 4 trouvé:",
        "my-PV Meter 4 ID encontrado:",
    ],
    "info_meter4_ip": [
        "gefundener my-PV Meter 4 IP:",
        "discovered my-PV Meter 4 IP:",
        "IP my-PV Meter 4 trouvé:",
        "my-PV Meter 4 IP encontrado:",
    ],
    "info_meter5_id": [
        "gefundener my-PV Meter 5 ID:",
        "discovered my-PV Meter 5 ID:",
        "ID my-PV Meter 5 trouvé:",
        "my-PV Meter 5 ID encontrado:",
    ],
    "info_meter5_ip": [
        "gefundener my-PV Meter 5 IP:",
        "discovered my-PV Meter 5 IP:",
        "IP my-PV Meter 5 trouvé:",
        "my-PV Meter 5 IP encontrado:",
    ],
    "info_meter6_id": [
        "gefundener my-PV Meter 6 ID:",
        "discovered my-PV Meter 6 ID:",
        "ID my-PV Meter 6 trouvé:",
        "my-PV Meter 6 ID encontrado:",
    ],
    "info_meter6_ip": [
        "gefundener my-PV Meter 6 IP:",
        "discovered my-PV Meter 6 IP:",
        "IP my-PV Meter 6 trouvé:",
        "my-PV Meter 6 IP encontrado:",
    ],
    "info_meter_ssid": [
        "WiFi Meter SSID",
        "WiFi Meter SSID",
        "WiFi Meter SSID",
        "WiFi Meter SSID",
    ],
    "info_meter_ss": [
        "WiFi Meter Signalstärke",
        "WiFi Meter signal strength",
        "Force du signal WiFi Meter",
        "Fuerza de la señal WiFi Meter",
    ],
    "info_surplus": [
        "Meter + Batterieladeleistung:",
        "Meter + battery charging:",
        "Meter + Puissance de charge batterie:",
        "Medidor + capacidad de carga de la batería:",
    ],
    "info_m0sum": [
        "Hausanschluss:",
        "Feed-in point:",
        "Raccordement maison:",
        "Conexión de la casa:",
    ],
    "info_m0l1": [
        "Hausanschluss L1:",
        "Feed-in point L1:",
        "Raccordement maison L1:",
        "Conexión de la casa L1:",
    ],
    "info_m0l2": [
        "Hausanschluss L2:",
        "Feed-in point L2:",
        "Raccordement maison L2:",
        "Conexión de la casa L2:",
    ],
    "info_m0l3": [
        "Hausanschluss L3:",
        "Feed-in point L3:",
        "Raccordement maison L3:",
        "Conexión de la casa L3:",
    ],
    "info_m0bat": [
        "Batteriespeicher:",
        "Battery:",
        "Stockage sur batterie:",
        "Acumulador:",
    ],
    "info_m1sum": [
        "Photovoltaik:",
        "Photovoltaic:",
        "Photovoltaïque:",
        "Fotovoltaico:",
    ],
    "info_m1l1": [
        "Photovoltaik L1:",
        "Photovoltaic L1:",
        "Photovoltaïque L1:",
        "Fotovoltaica L1:",
    ],
    "info_m1l2": [
        "Photovoltaik L2:",
        "Photovoltaic L2:",
        "Photovoltaïque L2:",
        "Fotovoltaica L2:",
    ],
    "info_m1l3": [
        "Photovoltaik L3:",
        "Photovoltaic L3:",
        "Photovoltaïque L3:",
        "Fotovoltaica L3:",
    ],
    "info_m1devstate": [
        "Photovoltaik Kommunikationsstatus:",
        "Photovoltaic communication state:",
        "État communication photovoltaïque:",
        "Estado de la comunicación Fotovoltaica:",
    ],
    "info_m2sum": [
        "Batteriespeicher:",
        "Battery sum:",
        "Stockage sur batterie:",
        "Acumulador:",
    ],
    "info_m2l1": [
        "Batteriespeicher L1:",
        "Battery L1:",
        "Stockage sur batterie L1:",
        "Acumulador L1:",
    ],
    "info_m2l2": [
        "Batteriespeicher L2:",
        "Battery L2:",
        "Stockage sur batterie L2:",
        "Acumulador L2:",
    ],
    "info_m2l3": [
        "Batteriespeicher L3:",
        "Battery L3:",
        "Stockage sur batterie L3:",
        "Acumulador L3:",
    ],
    "info_m2soc": [
        "Batteriespeicher SoC:",
        "Battery SoC:",
        "Stockage sur batterie SoC:",
        "Acumulador SoC:",
    ],
    "info_m2state": [
        "Batterie Status:",
        "Battery state:",
        "État batterie:",
        "Estado batería:",
    ],
    "info_m2devstate": [
        "Batteriespeicher Kommunikationsstatus:",
        "Battery communication state:",
        "État communication stockage sur batterie:",
        "Estado de comunicación acumulador:",
    ],
    "info_m3sum": ["E-Auto:", "EV:", "E-Auto:", "E-Auto:"],
    "info_m3l1": ["E-Auto L1:", "EV L1:", "E-Auto L1:", "E-Auto L1:"],
    "info_m3l2": ["E-Auto L2:", "EV L2:", "E-Auto L2:", "E-Auto L2:"],
    "info_m3l3": ["E-Auto L3:", "EV L3:", "E-Auto L3:", "E-Auto L3:"],
    "info_m3soc": ["E-Auto SoC:", "EV SoC:", "E-Auto SoC:", "E-Auto SoC:"],
    "info_m3devstate": [
        "E-Auto Kommunikationsstatus:",
        "EV communication state:",
        "État communication E-Auto:",
        "Estado de la comunicación E-Auto:",
    ],
    "info_m4sum": [
        "Wärmepumpe:",
        "Heat pump:",
        "Pompe à chaleur:",
        "Bomba de calentamiento:",
    ],
    "info_m4l1": [
        "Wärmepumpe L1:",
        "Heat pump L1:",
        "Pompe à chaleur L1:",
        "Bomba de calentamiento L1:",
    ],
    "info_m4l2": [
        "Wärmepumpe L2:",
        "Heat pump L2:",
        "Pompe à chaleur L2:",
        "Bomba de calentamiento L2:",
    ],
    "info_m4l3": [
        "Wärmepumpe L3:",
        "Heat pump L3:",
        "Pompe à chaleur L3:",
        "Bomba de calentamiento L3:",
    ],
    "info_m4devstate": [
        "Wärmepumpe Kommunikationsstatus:",
        "Heat pump communication state:",
        "État communication pompe à chaleur:",
        "Estado de comunicación de la bomba de calentamiento:",
    ],
    "info_measure_devstate_err1": [
        "Lesefehler Meter Register",
        "Error reading Meter Register",
        "Erreur de lecture registre Meter",
        "Error de lectura registro del medidor",
    ],
    "info_measure_devstate_err2": [
        "Lesefehler L1/L2/L3 Register",
        "Error reading L1/L2/L3 Registers",
        "Erreur de lecture registres L1/L2/L3",
        "Error de lectura registro L1/L2/L3",
    ],
    "info_measure_devstate_err3": [
        "Lesefehler SoC Register",
        "Error reading SoC Register",
        "Erreur de lecture registre SoC",
        "Error de lectura registro SoC",
    ],
    "info_measure_devstate_err4": [
        "Lesefehler Status Register",
        "Error reading State Register",
        "Erreur de lecture registre état",
        "Error de lectura registro de estado",
    ],
    "info_mss2": [
        "Sekundärregler 2 Status:",
        "Slave state 2:",
        "État régulateur secondaire 2:",
        "Controlador secundario 2 Estado:",
    ],
    "info_mss3": [
        "Sekundärregler 3 Status:",
        "Slave state 3:",
        "État régulateur secondaire 3:",
        "Controlador secundario 3 Estado:",
    ],
    "info_mss4": [
        "Sekundärregler 4 Status:",
        "Slave state 4:",
        "État régulateur secondaire 4:",
        "Controlador secundario 4 Estado:",
    ],
    "info_mss5": [
        "Sekundärregler 5 Status:",
        "Slave state 5:",
        "État régulateur secondaire 5:",
        "Controlador secundario 5 Estado:",
    ],
    "info_mss6": [
        "Sekundärregler 6 Status:",
        "Slave state 6:",
        "État régulateur secondaire 6:",
        "Controlador secundario 6 Estado:",
    ],
    "info_mss7": [
        "Sekundärregler 7 Status:",
        "Slave state 7:",
        "État régulateur secondaire 7:",
        "Controlador secundario 7 Estado:",
    ],
    "info_mss8": [
        "Sekundärregler 8 Status:",
        "Slave state 8:",
        "État régulateur secondaire 8:",
        "Controlador secundario 8 Estado:",
    ],
    "info_mss9": [
        "Sekundärregler 9 Status:",
        "Slave state 9:",
        "État régulateur secondaire 9:",
        "Controlador secundario 9 Estado:",
    ],
    "info_mss10": [
        "Sekundärregler 10 Status:",
        "Slave state 10:",
        "État régulateur secondaire 10:",
        "Controlador secundario 10 Estado:",
    ],
    "info_mss11": [
        "Sekundärregler 11 Status:",
        "Slave state 11:",
        "État régulateur secondaire 11:",
        "Controlador secundario 11 Estado:",
    ],
    "info_umains1": [
        "Eingangsspannung Leistungsteil L1:",
        "Input voltage power stage L1:",
        "Tension d'entrée étage de puissance L1:",
        "Voltaje de entrada L1:",
    ],
    "info_imains1": [
        "Netzstrom L1:",
        "Current L1:",
        "Courant réseau L1:",
        "Corriente red L1:",
    ],
    "info_umains2": [
        "Eingangsspannung Leistungsteil L2:",
        "Input voltage power stage L2:",
        "Tension d'entrée étage de puissance L2:",
        "Voltaje de entrada L2:",
    ],
    "info_imains2": [
        "Netzstrom L2:",
        "Current L2:",
        "Courant réseau L2:",
        "Corriente red L2:",
    ],
    "info_umains3": [
        "Eingangsspannung Leistungsteil L3:",
        "Input voltage power stage L3:",
        "Tension d'entrée étage de puissance L3:",
        "Voltaje de entrada L3:",
    ],
    "info_imains3": [
        "Netzstrom L3:",
        "Current L3:",
        "Courant réseau L3:",
        "Corriente red L3:",
    ],
    "info_uout": [
        "Ausgangsspannung Leistungsteil:",
        "Output voltage power stage:",
        "Tension de sortie étage de puissance:",
        "Voltaje de salida:",
    ],
    "info_freq": [
        "Netzfrequenz:",
        "Mains frequency:",
        "Fréquence réseau:",
        "Frecuencia red:",
    ],
    "info_temp_ps": [
        "Temperatur Leistungsteil:",
        "Temperature power stage:",
        "Température étage de puissance:",
        "Temeratura sección de potencia:",
    ],
    "info_fanspeed": [
        "Lüfter Stufe:",
        "Fan speed:",
        "Vitesse ventilateur:",
        "Velocidad del ventilador:",
    ],
    "info_ps_state": [
        "Status Leistungsteil:",
        "State power stage:",
        "État étage de puissance:",
        "Estado de la sección de potencia:",
    ],
    "info_ps_state_txt1": [
        "Warte auf Startup",
        "Wait for startup",
        "En attente de démarrage",
        "Esperar el inicio",
    ],
    "info_ps_state_txt2": ["Startup", "Startup", "Démarrage", "Inicio"],
    "info_ps_state_txt3": ["Läuft", "Running", "En marche", "En marcha"],
    "info_ps_state_txt4": ["Fehler", "Error", "Erreur", "Error"],
    "info_cloudstate": [
        "Cloud Status:",
        "Cloud state:",
        "État Cloud:",
        "Estado Cloud:",
    ],
    "info_cloudstate_0": [
        ", Nicht verbunden",
        ", Disconnected",
        ", Déconnecté",
        ", Desconectado",
    ],
    "info_cloudstate_1": [
        ", Warte auf DNS",
        ", Wait for DNS",
        ", Attendre le DNS",
        ", Esperar por el DNS",
    ],
    "info_cloudstate_2": [
        ", Warte auf Socket",
        ", Wait for socket",
        ", Attendre la prise",
        ", Espere por el enchufe",
    ],
    "info_cloudstate_3": [
        ", Verbindungsaufbau",
        ", Connecting",
        ", Connexion",
        ", Conectando",
    ],
    "info_cloudstate_4": [", Verbunden", ", Connected", ", Connecté", ", Conectado"],
    "info_cloudstate_5": [", Verbunden", ", Connected", ", Connecté", ", Conectado"],
    "info_cloudstate_6": [", Verbunden", ", Connected", ", Connecté", ", Conectado"],
    "info_cloudstate_99": [", Timeout", ", Timeout", ", Timeout", ", Tiempo de espera"],
    "info_debug_ip": ["Debug IP:", "Debug IP:", "IP Débogage:", "IP Debug:"],
    "info_cur_eth_mode": [
        "Ethernet-Modus:",
        "Ethernet-Mode:",
        "Mode Ethernet:",
        "Modo Ethernet:",
    ],
    "info_meter_v1": ["Spannung L1", "Voltage L1", "Tension L1", "Voltaje L1"],
    "info_meter_v2": ["Spannung L2", "Voltage L2", "Tension L2", "Voltaje L2"],
    "info_meter_v3": ["Spannung L3", "Voltage L3", "Tension L3", "Voltaje L3"],
    "info_meter_i1": ["Strom L1", "Current L1", "Courant L1", "Amperaje L1"],
    "info_meter_i2": ["Strom L2", "Current L2", "Courant L2", "Amperaje L2"],
    "info_meter_i3": ["Strom L3", "Current L3", "Courant L3", "Amperaje L3"],
    "info_meter_p1": ["Leistung L1", "Power L1", "Puissance L1", "Potencia L1"],
    "info_meter_p2": ["Leistung L2", "Power L2", "Puissance L2", "Potencia L2"],
    "info_meter_p3": ["Leistung L3", "Power L3", "Puissance L3", "Potencia L3"],
    "info_meter_es1": [
        "Netzbezug L1",
        "Grid supply L1",
        "Approvisionnement du réseau L1",
        "Suministro de la red L1",
    ],
    "info_meter_es2": [
        "Netzbezug L2",
        "Grid supply L2",
        "Approvisionnement du réseau L2",
        "Suministro de la red L2",
    ],
    "info_meter_es3": [
        "Netzbezug L3",
        "Grid supply L3",
        "Approvisionnement du réseau L3",
        "Suministro de la red L3",
    ],
    "info_meter_ef1": [
        "Netzeinspeisung L1",
        "Feed-in L1",
        "Alimentation du réseau L1",
        "Suministro a la red L1",
    ],
    "info_meter_ef2": [
        "Netzeinspeisung L2",
        "Feed-in L2",
        "Alimentation du réseau L2",
        "Suministro a la red L2",
    ],
    "info_meter_ef3": [
        "Netzeinspeisung L3",
        "Feed-in L3",
        "Alimentation du réseau L3",
        "Suministro a la red L3",
    ],
    "info_meter_f": [
        "Netzfrequenz",
        "Mains frequency",
        "Fréquence réseau",
        "Frecuencia de la red",
    ],
    "info_pmeter_ssid": [
        "WiFi Meter SSID",
        "WiFi Meter SSID",
        "WiFi Meter SSID",
        "WiFi Meter SSID",
    ],
    "info_pmeter_signal": [
        "WiFi Meter Signalstärke",
        "WiFi Meter signal strength",
        "Force du signal WiFi Meter",
        "Fuerza de la señal WiFi Meter",
    ],
    "home_heatstate": [
        "Heizleistung",
        "Heating power",
        "Puissance chauffage",
        "Potencia",
    ],
    "home_state": [
        "Gerätestatus",
        "Device state",
        "État dispositif",
        "Estado del dispositivo",
    ],
    "home_state1": ["Aus", "Off", "Désactivé", "Apagado"],
    "home_state2": ["Ein", "On", "Activé", "Encendido"],
    "mode": ["Betriebsart", "Mode", "Mode de fonctionnement", "Modo de funcionamiento"],
    "mode_m": [
        "Betriebsart:",
        "Mode:",
        "Mode de fonctionnement:",
        "Modo de funcionamiento:",
    ],
    "mode_m1": [
        "1: Warmwasser 3kW",
        "1: Hot water 3kW",
        "1: Eau chaude 3kW",
        "1: Agua caliente 3kW",
    ],
    "mode_m1_acthor9s": [
        "1: Warmwasser 9kW",
        "1: Hot water 9kW",
        "1: Eau chaude 9kW ",
        "1: Agua caliente 9kW",
    ],
    "mode_m1_elwa2": [
        "1: Warmwasser 3.6kW",
        "1: Hot water 3.6kW",
        "1: Eau chaude 3.6kW ",
        "1: Agua caliente 3.6kW",
    ],
    "mode_m2": [
        "2: Warmwasser Schichtladung",
        "2: Hot water stratification charge",
        "2: Chargement par stratification eau chaude",
        "2: Carga estratificada de agua caliente",
    ],
    "mode_m3": [
        "3: Warmwasser 6kW",
        "3: Hot water 6kW",
        "3: Eau chaude 6kW ",
        "3: Agua caliente 6kW",
    ],
    "mode_m3_acthor9s": [
        "3: Warmwasser 18kW",
        "3: Hot water 18kW",
        "3: Eau chaude 18kW ",
        "3: Agua caliente 18kW",
    ],
    "mode_m3_elwa2": [
        "3: Warmwasser 7.2kW",
        "3: Hot water 7.2kW",
        "3: Eau chaude 7.2kW ",
        "3: Agua caliente 7.2kW",
    ],
    "mode_m4": [
        "4: Warmwasser + Wärmepumpe",
        "4: Hot water + Heatpump",
        "4: Eau chaude + Pompe à chaleur ",
        "4: Agua caliente + bomba de calentamiento",
    ],
    "mode_m5": [
        "5: Warmwasser + Raumheizung",
        "5: Hot water + Spaceheating",
        "5: Eau chaude + Chauffage des locaux",
        "5: Agua caliente + Calentamiento del espacio",
    ],
    "mode_m6": [
        "6: Raumheizung 1 Kreis",
        "6: Spaceheating 1 Heater",
        "6: Chauffage des locaux 1 circuit",
        "6: Calentamiento espacio 1 circuito",
    ],
    "mode_m6_acthor9s": [
        "6: Raumheizung 3 Kreise",
        "6: Spaceheating 3 Heater",
        "6: Chauffage des locaux 3 circuits",
        "6: Calentamiento espacio 3 circuitos",
    ],
    "mode_m7": [
        "7: Warmwasser + PWM",
        "7: Hot water + PWM",
        "7: Eau chaude + PWM",
        "7: Agua caliente + PWM",
    ],
    "mode_m8": [
        "8: Frequenz-Modus",
        "8: Frequency-Mode",
        "8: Mode fréquence",
        "8: Modo frecuencia",
    ],
    "mode9s3x3": [
        "Lastpriorität:",
        "Load priority:",
        "Priorité charge:",
        "Prioridad de carga:",
    ],
    "mode9s3x3_1": ["Ausgang 1-2-3", "Out 1-2-3", "Sortie 1-2-3", "Salida 1-2-3"],
    "mode9s3x3_2": ["Ausgang 3-2-1", "Out 3-2-1", "Sortie 3-2-1", "Salida 3-2-1"],
    "pidtargetdevmax": [
        "Regeltoleranz:",
        "Control tolerance:",
        "Tolérance de contrôle",
        "Tolerancia de control",
    ],
    "relayload0": [
        "Last an Relais:",
        "Load at relay:",
        "Charge au relais:",
        "Carga en el relé:",
    ],
    "relaymode0_txt": [
        "Wird an der geschalteten Last kein my-PV Meter zur Leistungsmessung verwendet, so kann die Leistungsanzeige des ACTHORs und die Energieaufzeichnung des Datenloggers diesen Verbrauch nicht berücksichtigen!",
        "If no my-PV Meter is used for power measurement at the switched load, the power display of the ACTHOR and the energy recording of the data logger cannot take this consumption into account!",
        "Si aucun Meter my-PV n'est utilisé pour mesurer la puissance à la charge commutée, l'affichage de la puissance de l'ACTHOR et l'enregistrement de l'énergie de l'enregistreur de données ne peuvent pas prendre en compte cette consommation !",
        "Si no se utiliza un medidor de potencia my-PV para la medición de la potencia en la carga conmutada, la pantalla de potencia del ACTHOR y el registro de energía del registrador de datos no pueden tener en cuenta este consumo.",
    ],
    "relayload1": [
        "Lastmessung an Relais mit my-PV Meter:",
        "Load measurement on relays with my-PV Meter:",
        "Mesure de la charge sur les relais avec le my-PV Meter:",
        "Medición de la carga en los relés con my-PV Meter:",
    ],
    "relaymode1_txt": [
        "Beim my-PV Power Meter ist die ID (Seriennummer) 7-stellig.<br>Beim my-PV WiFi Meter ist die ID (Seriennummer) 10-stellig.",
        "For the my-PV Power Meter, the ID (serial number) has 7 digits.<br>For the my-PV WiFi Meter, the ID (serial number) has 10 digits.",
        "Pour le my-PV Power Meter, l'ID (numéro de série) est composé de 7 chiffres.<br>Pour le my-PV WiFi Meter, l'ID (numéro de série) est composé de 10 chiffres.",
        "Para el my-PV Power Meter, el ID (número de serie) tiene 7 dígitos. Para el my-PV WiFi Meter, el ID (número de serie) tiene 10 dígitos.",
    ],
    "wws_elwa": [
        "Warmwasser-Sicherstellung",
        "Hot Water Boost",
        "Sécurisation eau chaude",
        "Boost agua caliente",
    ],
    "wws_acthor": ["Warmwasser", "Hot Water", "Eau chaude", "Agua caliente"],
    "wws_tmax": [
        "Temperatur max. - Solarbetrieb:",
        "Temperature max. - Solar powered:",
        "Température max. - Opération solaire:",
        "Temperatura máx. - Operación solar",
    ],
    "wws_tmax_txt": [
        "Nur relevant falls Sensor aktiviert.",
        "Only relevant if sensor activated.",
        "Seulement pertinent si le capteur est activé.",
        "Sólo es relevante si el sensor está activado.",
    ],
    "wws_bstmode": [
        "Sicherstellungs-Modus:",
        "Boost mode:",
        "Mode sécurisation:",
        "Modo boost:",
    ],
    "wws_bstmode0": ["Aus", "Off", "Désactivé", "Apagado"],
    "wws_bstmode1": ["Ein", "On", "Activé", "Encendido"],
    "wws_bstmode2": ["Ein", "On", "Activé", "Encendido"],
    "wws_bstmode3": ["Relais", "Relay", "Relais", "Relé"],
    "wws_elwa_bsttemp": [
        "Sicherstellungs-Temperatur:",
        "Boost temp:",
        "Température sécurisation:",
        "Boost-Temperatura:",
    ],
    "wws_acthor_bsttemp": [
        "Temperatur min:",
        "Temperature min:",
        "Température min.:",
        "Temperatura mín.",
    ],
    "wws_time1": [
        "Sicherstellung Zeitfenster 1 von / bis:",
        "Boost timeframe 1 from / to:",
        "Créneau horaire sécurisation 1 de / à:",
        "Boost ventana de tiempo 1 desde / hasta:",
    ],
    "wws_time2": [
        "Sicherstellung Zeitfenster 2 von / bis:",
        "Boost timeframe 2 from / to:",
        "Créneau horaire sécurisation 2 de / à:",
        "Boost ventana de tiempo 2 desde / hasta:",
    ],
    "wws_bstoutput": [
        "Sicherstellungs-Ausgang:",
        "Boost-Output",
        "Sortie sécurisation:",
        "Boost-Salida:",
    ],
    "wws_bstoutput7": ["1, 2 und 3", "1, 2 and 3", "1, 2 et 3", "1, 2 y 3"],
    "wws_bstoutput6": ["2 und 3", "2 and 3", "2 et 3", "2 y 3"],
    "wws_bstoutput4": ["3", "3", "3", "3"],
    "wws_bstwd1": ["Wochentag", "Weekday", "Jour de la semaine", "Día de la semana"],
    "legsch": [
        "Legionellenschutz",
        "Legionella Protection",
        "Protection anti-légionellose ",
        "Protección contra la legionela",
    ],
    "legsch_mode": [
        "Vermeidung von Legionellen:",
        "Avoidance of legionella:",
        "Fonction anti-légionellose:",
        "Función anti-legionela:",
    ],
    "legsch_mode0": ["Aus", "Off", "Désactivée", "Apagado"],
    "legsch_mode1": ["Ein", "On", "Activée", "Encendido"],
    "leg_bstoutput": [
        "Legionellen-Boost Ausgänge:",
        "Legionellen-Boost outputs:",
        "Sorties boost anti-légionellose:",
        "Salidas anti-legionela:",
    ],
    "leg_bstoutput7": ["1, 2 und 3", "1, 2 and 3", "1, 2 et 3", "1, 2 y 3"],
    "leg_bstoutput6": ["2 und 3", "1, 2 and 3", "2 et 3", "2 y 3"],
    "leg_bstoutput4": ["3", "3", "3", "3"],
    "legsch_int": [
        "Aktivierungs-Intervall:",
        "Activation intervall:",
        "Intervalle d'activation:",
        "Intervalo de activación:",
    ],
    "legsch_intu": ["Tage", "Days", "Jours", "Días"],
    "legsch_start": [
        "Start-Stunde:",
        "Start hour:",
        "Heure de départ:",
        "Hora de inicio:",
    ],
    "legsch_temp": [
        "Ziel-Temperatur:",
        "Target temp:",
        "Température cible:",
        "Temperatura objetivo:",
    ],
    "rh1": [
        "Raumheizung 1",
        "Spaceheating 1",
        "Chauffage des locaux 1",
        "Calentamiento espacio 1",
    ],
    "rh2": [
        "Raumheizung 2",
        "Spaceheating 2",
        "Chauffage des locaux 2",
        "Calentamiento espacio 2",
    ],
    "rh3": [
        "Raumheizung 3",
        "Spaceheating 3",
        "Chauffage des locaux 3",
        "Calentamiento espacio 3",
    ],
    "rh_temp": [
        "Temperatur max / min Tag / min Nacht",
        "Temperature max / min day / min night",
        "Température max. / min. jour / min. nuit",
        "Temperatura máx. / min. día / min. noche",
    ],
    "rh_wdnight": [
        "Wochenprogramm: Nacht von - bis",
        "Weekly program: Night during",
        "Programme hebdomadaire: Nuit de - à",
        "Programa semanal: Noche desde - hasta",
    ],
    "rh_wd1_from": ["Montag von:", "Monday from", "Lundi de:", "Lunes desde:"],
    "rh_wd1_to": ["Montag bis:", "Monday to", "Lundi jusqu'à:", "Lunes hasta:"],
    "rh_wd2_from": ["Dienstag von:", "Tuesday from:", "Mardi de:", "Martes desde:"],
    "rh_wd2_to": ["Dienstag bis:", "Tuesday to:", "Mardi jusqu'à:", "Martes hasta:"],
    "rh_wd3_from": [
        "Mittwoch von:",
        "Wednesday from:",
        "Mercredi de:",
        "Miércoles desde:",
    ],
    "rh_wd3_to": [
        "Mittwoch bis:",
        "Wednesday to:",
        "Mercredi jusqu'à:",
        "Miércoles hasta:",
    ],
    "rh_wd4_from": ["Donnerstag von:", "Thursday from:", "Jeudi de:", "Jueves de:"],
    "rh_wd4_to": ["Donnerstag bis:", "Thursday to:", "Jeudi jusqu'à:", "Jueves hasta:"],
    "rh_wd5_from": ["Freitag von:", "Friday from:", "Vendredi de:", "Viernes desde:"],
    "rh_wd5_to": ["Freitag bis:", "Friday to:", "Vendredi jusqu'à:", "Viernes hasta:"],
    "rh_wd6_from": ["Samstag von:", "Saturday from:", "Samedi de:", "Sábado desde:"],
    "rh_wd6_to": ["Samstag bis:", "Saturday to:", "Samedi jusqu'à:", "Sábado hasta:"],
    "rh_wd7_from": ["Sonntag von:", "Sunday from:", "Dimanche de:", "Domingo desde:"],
    "rh_wd7_to": ["Sonntag bis:", "Sunday to:", "Dimanche jusqu'à:", "Domingo hasta:"],
    "rh_wd_to": ["bis:", "to", "jusqu'à:", "hasta:"],
    "hyst_hw": [
        "Warmwasser max / min:",
        "Hot water max / min:",
        "Eau chaude max. / min.:",
        "Agua caliente max / min",
    ],
    "hyst_sh": [
        "Raumheizung max / min:",
        "Spaceheating max / min:",
        "Chauffage des locaux max. / min.:",
        "Calentamiento espacio max / min",
    ],
    "hyst": ["Hysteresen", "Hysteresis", "Hystérésis", "Histéresis"],
    "relay": [
        "Schalt-Funktion",
        "Relay-Function",
        "Fonction de commutation",
        "Función de conmutación",
    ],
    "relay_lev": [
        "Leistungsschwelle:",
        "Power threshold:",
        "Seuil de puissance:",
        "Umbral de potencia:",
    ],
    "relay_mde": [
        "ACTHOR regelt wenn Relais ein:",
        "ACTHOR regulates when relay is on:",
        "ACTHOR contrôle quand le relais est activé:",
        "ACTHOR controla cuando el relé ha activado:",
    ],
    "relay_mde_elwa2": [
        "AC ELWA-2 regelt wenn Relais ein:",
        "AC ELWA-2 regulates when relay is on:",
        "AC ELWA-2 contrôle quand le relais est activé:",
        "AC ELWA-2 controla cuando el relé ha activado:",
    ],
    "schalt_mde0": ["Aus", "Off", "Désactivé", "Apagado"],
    "schalt_mde1": ["Ein", "On", "Activée", "Encendido"],
    "relay_t1": [
        "Zeit Schwellen-Überschreitung:",
        "Time threshold exceeded:",
        "Dépassement du seuil temporel:",
        "Umbral de tiempo superado:",
    ],
    "relay_t2": [
        "Min. Zeit ein:",
        "Min. time on:",
        "Temps min. activé:",
        "Tiempo mínimo activado:",
    ],
    "relay_t3": [
        "Min. Zeit aus:",
        "Min. time off:",
        "Temps min. désactivé:",
        "Min. tiempo apagado:",
    ],
    "fmode": ["Frequenz-Modus", "Frequency-Mode", "Mode fréquence ", "Modo frecuencia"],
    "fmode_from_to": [
        "Frequenz von / bis",
        "Frequency start / stop",
        "Fréquence de / à",
        "Frecuencia dedes / hasta",
    ],
    "time": ["Uhrzeit", "Time", "Heure", "Hora"],
    "time_elwa": [
        "Aktuelle Uhrzeit AC ELWA:",
        "Current AC ELWA time:",
        "Heure actuelle AC ELWA:",
        "Hora actual AC ELWA:",
    ],
    "time_acthor": [
        "Aktuelle Uhrzeit AC-THOR:",
        "Current AC-THOR time:",
        "Heure actuelle AC-THOR:",
        "Hora actual AC-THOR:",
    ],
    "time_elwa2": [
        "Aktuelle Uhrzeit AC ELWA-2",
        "Current AC ELWA-2 time:",
        "Heure actuelle AC ELWA-2:",
        "Hora actual AC ELWA-2:",
    ],
    "time_elwa_utc": [
        "AC ELWA Zeitzone:",
        "AC ELWA timezone:",
        "Fuseau horaire AC ELWA:",
        "Zona horaria AC ELWA:",
    ],
    "time_acthor_utc": [
        "AC-THOR Zeitzone:",
        "AC-THOR timezone:",
        "Fuseau horaire AC-THOR:",
        "Zona horaria AC-THOR:",
    ],
    "time_utcsave": [
        "(Speichern drücken um upzudaten)",
        "(Press save to update)",
        "(Appuyez sur sauvegarder pour mettre à jour)",
        "(Presione guardar para actualizar)",
    ],
    "time_pcutc": [
        "PC Zeitzone:",
        "PC timezone:",
        "Fuseau horaire PC:",
        "Zona horaria del PC:",
    ],
    "time_dst_on": [
        "Sommerzeit Automatik:",
        "Daylight saving mode:",
        "Heure d'été automatique:",
        "Horario de verano automático:",
    ],
    "time_dst_on0": ["Aus", "Off", "Désactivée", "Apagado"],
    "time_dst_on1": ["Ein", "On", "Activée", "Encendido"],
    "time_ntpip": [
        "Zeitserver IP Adresse:",
        "NTP server IP address:",
        "Adresse IP du serveur temporel:",
        "Dirección IP del servidor de NTP:",
    ],
    "time_region": ["Region:", "Region:", "Région:", "Región:"],
    "time_city": ["Ort:", "Location:", "Localisation:", "Ubicación:"],
    "time_ntpurl": [
        "Zeitserver:",
        "NTP server:",
        "serveur temporel:",
        "servidor de NTP:",
    ],
    "time_pc": ["Zeit:", "Time:", "Heure:", "Hora:"],
    "control": [
        "Steuerungs-Einstellungen",
        "Control Settings",
        "Paramétrages des commandes",
        "Ajustes de control",
    ],
    "ctrltype": [
        "Ansteuerungs-Typ:",
        "Control type:",
        "Type de contrôle:",
        "Tipo de conducción:",
    ],
    "ctrltype_txt_elwa": [
        "ELWA Nummer >1: nur 'Slave' einstellbar.",
        "ELWA Number >1: only 'Slave' selectable.",
        "ELWA numéro >1: réglage 'Slave' uniquement.",
        "Número ELWA >1: sólo se puede configurar 'Esclavo'.",
    ],
    "ctrltype_txt_acthor": [
        "AC-THOR Nummer >1: nur 'Slave' einstellbar.",
        "AC-THOR Number >1: only 'Slave' selectable.",
        "AC-THOR numéro >1: réglage 'Slave' uniquement. ",
        "Número AC-THOR >1: sólo se puede configurar 'Esclavo'.",
    ],
    "ctrltype_tip": [
        'TIPP: Für viele Ansteuerungs-Typen gibt es eigene Anleitungen zu den erforderlichen Einstellungen.<br>Nähere Informationen finden sie <a href="https://www.my-pv.com/de/info/kompatible-hersteller" target="_blank">hier</a>.',
        'TIP: For many control types there are separate instructions for the required settings.<br>More information can be found <a href="https://www.my-pv.com/en/info/compatible-manufacturers" target="_blank">here</a>.',
        'ASTUCE : pour de nombreuses sources de signaux, il existe des instructions spécifiques concernant les réglages nécessaires.<br>Vous trouverez de plus amples informations <a href="https://www.my-pv.com/fr/infos/fabricants-de-produits-compatibles" target="_blank">ici</a>.',
        'CONSEJO: Para muchos tipos de control, hay instrucciones separadas para los ajustes necesarios.<br>Puede encontrar más información <a href="https://www.my-pv.com/es/informacion/fabricantes-compatibles" target="_blank">aquí</a>.',
    ],
    "ctrltype0": ["Auto Detect", "Auto Detect", "Auto Detect", "Auto Detección"],
    "ctrltype1": ["HTTP", "HTTP", "HTTP", "HTTP"],
    "ctrltype2": ["Modbus TCP", "Modbus TCP", "Modbus TCP", "Modbus TCP"],
    "ctrltype3": ["Fronius Auto", "Fronius Auto", "Fronius Auto", "Fronius Auto"],
    "ctrltype4": [
        "Fronius Manual",
        "Fronius Manual",
        "Fronius Manual",
        "Fronius Manual",
    ],
    "ctrltype5": [
        "SMA Home Manager",
        "SMA Home Manager",
        "SMA Home Manager",
        "SMA Home Manager",
    ],
    "ctrltype6": ["Steca Auto", "Steca Auto", "Steca Auto", "Steca Auto"],
    "ctrltype7": ["Varta Auto", "Varta Auto", "Varta Auto", "Varta Auto"],
    "ctrltype8": ["Varta Manual", "Varta Manual", "Varta Manual", "Varta Manual"],
    "ctrltype9": ["Slave", "Slave", "Slave", "Esclavo"],
    "ctrltype10": [
        "RCT Power Manual",
        "RCT Power Manual",
        "RCT Power Manual",
        "RCT Power Manual",
    ],
    "ctrltype11": [
        "Adjustable Modbus TCP (Sunspec etc)",
        "Adjustable Modbus TCP (Sunspec etc)",
        "Adjustable Modbus TCP (Sunspec etc)",
        "Modbus TCP ajustable (Sunspec etc.)",
    ],
    "ctrltype12": [
        "my-PV Meter Auto",
        "my-PV Meter Auto",
        "my-PV Meter Auto",
        "my-PV Meter Auto",
    ],
    "ctrltype13": [
        "my-PV Meter Manual",
        "my-PV Meter Manual",
        "my-PV Meter Manual",
        "my-PV Meter Manual",
    ],
    "ctrltype14": [
        "my-PV Power Meter Direkt",
        "my-PV Power Meter Direct",
        "my-PV Power Meter Direct",
        "my-PV Power Meter Direct",
    ],
    "ctrltype15": ["Modbus RTU", "Modbus RTU", "Modbus RTU", "Modbus RTU"],
    "ctrltype16": [
        "Adjustable Modbus RTU",
        "Adjustable Modbus RTU",
        "Adjustable Modbus RTU",
        "Modbus RTU ajustable",
    ],
    "ctrltype17": [
        "SMA Direkte Zähler Kommunikation Auto",
        "SMA Direct meter communication Auto",
        "SMA Direct meter communication Auto",
        "SMA Direct meter communication Auto",
    ],
    "ctrltype18": [
        "SMA Direkte Zähler Kommunikation Manual",
        "SMA Direct meter communication Manual",
        "SMA Direct meter communication Manual",
        "SMA Direct meter communication Manual",
    ],
    "ctrltype19": [
        "Digital Meter P1",
        "Digital Meter P1",
        "Digital Meter P1",
        "Digital Meter P1",
    ],
    "ctrltype20": ["Frequenz", "Frequency", "Fréquence", "Frecuencia"],
    "ctrltype100": [
        "Fronius Sunspec Manual",
        "Fronius Sunspec Manual",
        "Fronius Sunspec Manual",
        "Fronius Sunspec Manual",
    ],
    "ctrltype101": [
        "KACO TL1 + TL3 Manual",
        "KACO TL1 + TL3 Manual",
        "KACO TL1 + TL3 Manual",
        "KACO TL1 + TL3 Manual",
    ],
    "ctrltype102": [
        "Kostal PIKO IQ Plenticore plus Manual",
        "Kostal PIKO IQ Plenticore plus Manual",
        "Kostal PIKO IQ Plenticore plus Manual",
        "Kostal PIKO IQ Plenticore plus Manual",
    ],
    "ctrltype103": [
        "Kostal Smart Energy Meter Manual",
        "Kostal Smart Energy Meter Manual",
        "Kostal Smart Energy Meter Manual",
        "Kostal Smart Energy Meter Manual",
    ],
    "ctrltype104": [
        "MEC electronics Manual",
        "MEC electronics Manual",
        "MEC electronics Manual",
        "MEC electronics Manual",
    ],
    "ctrltype105": [
        "SolarEdge Manual",
        "SolarEdge Manual",
        "SolarEdge Manual",
        "SolarEdge Manual",
    ],
    "ctrltype114": [
        "SolarEdge Syn.2unit Manual",
        "SolarEdge Syn.2unit Manual",
        "SolarEdge Syn.2unit Manual",
        "SolarEdge Syn.2unit Manual",
    ],
    "ctrltype115": [
        "SolarEdge Syn.3unit Manual",
        "SolarEdge Syn.3unit Manual",
        "SolarEdge Syn.3unit Manual",
        "SolarEdge Syn.3unit Manual",
    ],
    "ctrltype106": [
        "Victron Energy 1ph Manual",
        "Victron Energy 1ph Manual",
        "Victron Energy 1ph Manual",
        "Victron Energy 1ph Manual",
    ],
    "ctrltype107": [
        "Victron Energy 3ph Manual",
        "Victron Energy 3ph Manual",
        "Victron Energy 3ph Manual",
        "Victron Energy 3ph Manual",
    ],
    "ctrltype108": [
        "Huawei (Modbus TCP) Manual",
        "Huawei (Modbus TCP) Manual",
        "Huawei (Modbus TCP) Manual",
        "Huawei (Modbus TCP) Manual",
    ],
    "ctrltype109": [
        "Carlo Gavazzi EM24 Manual",
        "Carlo Gavazzi EM24 Manual",
        "Carlo Gavazzi EM24 Manual",
        "Carlo Gavazzi EM24 Manual",
    ],
    "ctrltype110": [
        "SolarEdge 1502 Manual",
        "SolarEdge 1502 Manual",
        "SolarEdge 1502 Manual",
        "SolarEdge 1502 Manual",
    ],
    "ctrltype111": [
        "Sungrow Manual",
        "Sungrow Manual",
        "Sungrow Manual",
        "Sungrow Manual",
    ],
    "ctrltype112": [
        "Fronius Gen24 Manual",
        "Fronius Gen24 Manual",
        "Fronius Gen24 Manual",
        "Fronius Gen24 Manual",
    ],
    "ctrltype113": ["GoodWe Manual", "GoodWe Manual", "GoodWe Manual", "GoodWe Manual"],
    "ctrltype200": [
        "Huawei (Modbus RTU)",
        "Huawei (Modbus RTU)",
        "Huawei (Modbus RTU)",
        "Huawei (Modbus RTU)",
    ],
    "ctrltype201": [
        "Growatt (Modbus RTU)",
        "Growatt (Modbus RTU)",
        "Growatt (Modbus RTU)",
        "Growatt (Modbus RTU)",
    ],
    "ctrltype202": [
        "Solax (Modbus RTU)",
        "Solax (Modbus RTU)",
        "Solax (Modbus RTU)",
        "Solax (Modbus RTU)",
    ],
    "ctrltype203": [
        "QCELLS (Modbus RTU)",
        "QCELLS (Modbus RTU)",
        "QCELLS (Modbus RTU)",
        "QCELLS (Modbus RTU)",
    ],
    "ctrltype204": [
        "IME Conto D4 Modbus MID (Modbus RTU)",
        "IME Conto D4 Modbus MID (Modbus RTU)",
        "IME Conto D4 Modbus MID (Modbus RTU)",
        "IME Conto D4 Modbus MID (Modbus RTU)",
    ],
    "control_ip": [
        "IP Adresse der Ansteuerung:",
        "Control source IP address:",
        "Adresse IP de la commande:",
        "Dirección IP del controlador:",
    ],
    "control_devid": [
        "Geräte ID:",
        "Device ID:",
        "ID dispositif:",
        "Identificación de los dispositivos:",
    ],
    "control_port": [
        "Geräte Port:",
        "Device port:",
        "Port dispositif:",
        "Puerto de los dispositivos:",
    ],
    "control_baud": ["Baudrate:", "Baud rate:", "Baud:", "Baudrate:"],
    "control_parity": ["Parity:", "Parity:", "Parité:", "Paridad:"],
    "control_stopbit": ["Stop Bits:", "Stop bits:", "Bits d'arrêt:", "Bits de parada:"],
    "control_regrange": [
        "Registerbereich:",
        "Register range:",
        "Zone de registre",
        "Rango de registro",
    ],
    "control_sign": ["Vorzeichen:", "Sign:", "Signe:", "Señal:"],
    "control_mreg": [
        "Meter Register:",
        "Meter register:",
        "Registre Meter:",
        "Registro del medidor:",
    ],
    "control_mreg_sep_feedin": [
        "Separates Meter Register für Einspeisung<br>(0 wenn nicht vorhanden):",
        "Separate meter register for feed-in<br>(0 if not present):",
        "Registre Meter séparé pour l'injection<br>(0 s'il n'est pas présent):",
        "Registro del medidor separado para feed-in<br>(0 si no está presente):",
    ],
    "control_sreg": [
        "Skalierungsregister:",
        "Scale register:",
        "Registre de mise à l'échelle:",
        "Registro escala:",
    ],
    "control_mregl": [
        "L1/L2/L3 Register:",
        "L1/L2/L3 registers:",
        "Registres L1/L2/L3:",
        "Registro L1/L2/L3:",
    ],
    "control_mregtypel": [
        "L1/L2/L3 Typ:",
        "L1/L2/L3 type:",
        "Type L1/L2/L3:",
        "Tipo L1/L2/L3:",
    ],
    "control_sregl": [
        "L1/L2/L3 Skalierungsregister:",
        "L1/L2/L3 scale registers:",
        "Registres de mise à l'échelle L1/L2/L3:",
        "Registro de escala L1/L2/L3:",
    ],
    "control_sregtypel": [
        "L1/L2/L3 Skalierungsregister-Typ:",
        "L1/L2/L3 scale registers type:",
        "Type de registre de mise à l'échelle L1/L2/L3:",
        "Tipo de registro de escala L1/L2/L3:",
    ],
    "control_signbat": [
        "Batterie Ladeleistung Vorzeichen:",
        "Battery charging power sign:",
        "Signe puissance de charge batterie:",
        "Señal potencia carga batería:",
    ],
    "control_mregbat": [
        "Batterie Ladeleistung Register:",
        "Battery charging power register:",
        "Registre puissance de charge batterie:",
        "Registro Potencia carga batería:",
    ],
    "control_sregbat": [
        "Batterie Ladeleistung Skalierungsregister:",
        "Battery charging power scale register:",
        "Registre de mise à l'échelle puissance de charge batterie:",
        "Registro escala potencia carga batería:",
    ],
    "control_state": [
        "Status Ansteuerung:",
        "Control state:",
        "État de commande: ",
        "Estado de control:",
    ],
    "control_tout": [
        "Zeitablauf Ansteuerung:",
        "Power timeout:",
        "Délais de dépassement commande:",
        "Control de tiempo de espera:",
    ],
    "control_ptarget": [
        "Zielwert der Regelung:",
        "Control target:",
        "Valeur cible contrôle:",
        "Valor objetivo control:",
    ],
    "control_ptarget_txt": [
        "Negativer Wert bedeutet Einspeisung. Verändern Sie diesen Wert nur, wenn Sie mit der Regelungsstrategie vertraut sind - siehe Hilfe für weitere Details.",
        "Negative value means feed-in. Only change this value if you are familiar with the control strategy - read Help for more details.",
        "Une valeur négative signifie une injection. Ne modifiez cette valeur que si vous connaissez bien la stratégie de contrôle - voir l'aide pour plus de détails.",
        "El valor negativo significa que se exporta. Sólo cambia este valor si estás familiarizado con la estrategia de control - ver Ayuda para más detalles.",
    ],
    "ptarget2_mode": [
        "Intervall-Zielwert:",
        "Interval target value:",
        "Valeur cible de l'intervalle:",
        "Valor objetivo del intervalo:",
    ],
    "ptarget2_mode0": ["Aus", "Off", "Désactivée", "Apagado"],
    "ptarget2_mode1": ["Ein", "On", "Activée", "Encendido"],
    "control_ptarget2": [
        "Intervall-Zielwert der Regelung:",
        "Interval target value of the control:",
        "Valeur cible de l'intervalle de la régulation:",
        "Valor objetivo de intervalo del control:",
    ],
    "control_ptarget2_txt": [
        "Intervall-Zielwert: Wenn aktiv, wird im eingestellten Zeitfenster ein anderer Zielwert der Regelung verwendet.",
        "Interval target value: If active, a different target value of the control is used in the set time window.",
        "Valeur cible de l'intervalle : si elle est active, une autre valeur cible de la régulation est utilisée dans la fenêtre temporelle réglée.",
        "Valor objetivo del intervalo: Si está activo, se utiliza un valor objetivo diferente del control en la ventana de tiempo establecida.",
    ],
    "control_pt2_int": ["Intervall:", "Interval", "Intervalle:", "Intervalo:"],
    "control_pt2_t1": [
        "Dauer des Intervall-Zielwerts:",
        "Duration of the interval target value:",
        "Durée de la valeur cible de l'intervalle:",
        "Duración del valor objetivo del intervalo:",
    ],
    "control_startstop": [
        "Sperre Start / Stop Stunde:",
        "Block start / stop hour:",
        "Heure de début / fin de blocage:",
        "Hora de inicio / hora de terminación de parada:",
    ],
    "measure": [
        "Messwerte-Einstellungen",
        "Measurement Settings",
        "Réglages des valeurs mesurées",
        "Ajustes de los valores medidos",
    ],
    "measure_help": [
        "Die Erfassung überschüssiger Leistung am Hausanschluss erfolgt bereits durch das zur Ansteuerung konfigurierte Gerät (siehe Steuerungs-Einstellungen). Diese Messgrößen können darüber hinaus optional zur Darstellung der Werte in der my-PV.LIVE Cloud erfasst werden. Sie haben für den Regelbetrieb des my-PV Geräts keine Relevanz.",
        "Excess power in the grid feed-in point is already detected by the device configured for control (see Control Settings). In addition, these measured variables can optionally be detected for display in the my-pv.LIVE cloud. They have no relevance for the operation of the my-PV device.",
        "Un excès de puissance au niveau du raccordement maison est déjà détecté par l'appareil configuré pour le contrôle (voir Paramétrage des commandes). En outre, ces variables mesurées peuvent être enregistrées en option pour la représentation des valeurs dans le cloud my-pv.LIVE. Elles n'ont aucun rapport avec le fonctionnement régulier du dispositif my-PV.",
        "El exceso de potencia en la conexión de la casa ya es detectado por el dispositivo configurado para el control (véase Ajustes de control). Además, estas variables medidas pueden ser opcionalmente registradas para la representación de los valores en el cloud my-pv.LIVE. No tienen relevancia para el funcionamiento regular del dispositivo my-PV.",
    ],
    "measure_mode": [
        "Messwertquelle:",
        "Measure source:",
        "Source de valeur mesurée:",
        "Fuente de valor medido:",
    ],
    "mdevtype0": ["keine", "none", "aucune", "ninguna"],
    "mdevtype1": ["my-PV Meter", "my-PV Meter", "my-PV Meter", "my-PV Meter"],
    "mdevtype2": [
        "Adjustable Modbus TCP",
        "Adjustable Modbus TCP",
        "Adjustable Modbus TCP",
        "Modbus TCP ajustable",
    ],
    "measurem1": [
        "Leistung Photovoltaik",
        "Photovoltaic power",
        "Puissance photovoltaïque",
        "Energía fotovoltaica",
    ],
    "measurem2": [
        "Leistung Batterie",
        "Battery power",
        "Puissance batterie",
        "Energía de la batería",
    ],
    "measurem3": [
        "Leistung Ladestation",
        "EV Charging station power",
        "Puissance station de charge",
        "Estación de carga de energía",
    ],
    "measurem4": [
        "Leistung Wärmepumpe",
        "Heat pump power",
        "Puissance pompe à chaleur",
        "Salida de la bomba de calor",
    ],
    "measure_devtype": [
        "Gerätetyp:",
        "Device Type:",
        "Type de dispositif:",
        "Tipo dispositivo:",
    ],
    "measure_meterid": [
        "my-PV Meter ID:",
        "my-PV Meter ID:",
        "ID my-PV Meter:",
        "Meter my-PV:",
    ],
    "measure_meterid_info": [
        "Beim my-PV Power Meter ist die ID (Seriennummer) 7-stellig.<br>Beim my-PV WiFi Meter ist die ID (Seriennummer) 10-stellig.",
        "For the my-PV Power Meter, the ID (serial number) has 7 digits.<br>For the my-PV WiFi Meter, the ID (serial number) has 10 digits.",
        "Pour le my-PV Power Meter, l'ID (numéro de série) est composé de 7 chiffres.<br>Pour le my-PV WiFi Meter, l'ID (numéro de série) est composé de 10 chiffres.",
        "Para el my-PV Power Meter, el ID (número de serie) tiene 7 dígitos. Para el my-PV WiFi Meter, el ID (número de serie) tiene 10 dígitos.",
    ],
    "measure_ip": [
        "Modbus IP Adresse:",
        "Modbus IP address:",
        "Adresse IP Modbus:",
        "Dirección IP de Modbus:",
    ],
    "measure_devid_port": [
        "Geräte ID / Port:",
        "Device ID / Port:",
        "ID / port dispositif:",
        "ID / Puerto de los dispositivos:",
    ],
    "measure_regrange": [
        "Registerbereich:",
        "Register range:",
        "Zone de registre",
        "Rango de registro",
    ],
    "measure_sign": ["Vorzeichen:", "Sign:", "Signe:", "Señal:"],
    "measure_mreg": [
        "Meter Register:",
        "Meter register:",
        "Registre Meter: ",
        "Registro del medidor:",
    ],
    "measure_sreg": [
        "Skalierungsregister:",
        "Scale register:",
        "Registre de mise à l'échelle:",
        "Registro escala:",
    ],
    "measure_mregl": [
        "L1/L2/L3 Register:",
        "L1/L2/L3 registers:",
        "Registres L1/L2/L3: ",
        "Registro L1/L2/L3:",
    ],
    "measure_mregtypel": [
        "L1/L2/L3 Typ:",
        "L1/L2/L3 type:",
        "Type L1/L2/L3: ",
        "Tipo L1/L2/L3:",
    ],
    "measure_sregl": [
        "L1/L2/L3 Skalierungsregister:",
        "L1/L2/L3 scale registers:",
        "Registres de mise à l'échelle L1/L2/L3:",
        "Registro de escala L1/L2/L3:",
    ],
    "measure_sregtypel": [
        "L1/L2/L3 Skalierungsregister-Typ:",
        "L1/L2/L3 scale registers type:",
        "Type de registre de mise à l'échelle L1/L2/L3:",
        "Tipo de registro de escala L1/L2/L3:",
    ],
    "measure_batsocreg": [
        "Batterie SoC Register:",
        "Battery SoC register:",
        "Registre SoC batterie:",
        "Registro SoC batería:",
    ],
    "measure_batsocsreg": [
        "Batterie SoC Skalierungsregister:",
        "Battery SoC scale register:",
        "Registre de mise à l'échelle SoC batterie:",
        "Registro escala SoC batería:",
    ],
    "measure_batstatereg": [
        "Batterie Statusregister:",
        "Battery state register",
        "Registre d'état batterie:",
        "Registro estado batería:",
    ],
    "measure_ecarsocreg": [
        "E-Auto SoC Register:",
        "EV SoC register:",
        "Registre SoC E-Auto:",
        "Registro SoC Vehículo Eléctrico:",
    ],
    "measure_ecarsocsreg": [
        "E-Auto SoC Skalierungsregister:",
        "EV SoC scale register:",
        "Registre de mise à l'échelle SoC E-Auto:",
        "Registro escala SoC Vehículo Eléctrico:",
    ],
    "measure_pv_block": [
        "Ohne PV-Leistung das Gerät sperren:",
        "Without PV power block device:",
        "Sans dispositif de bloc d'alimentation PV:",
        "Sin el dispositivo de bloqueo de energía fotovoltaica:",
    ],
    "measure_pv_block0": ["Aus", "Off", "Désactivé", "Apagado"],
    "measure_pv_block1": ["Ein", "On", "Activé", "Encendido"],
    "meas3_pt2_t2": [
        "Zusätzliche Dauer des Intervall-Zielwerts bei Leistungsbezug (> 500W) der Ladestation:",
        "Additional duration of the interval target value when power is drawn (> 500W) from the charging station.",
        "Durée supplémentaire de la valeur cible de l'intervalle en cas d'appel de puissance (> 500W) de la station de recharge:",
        "Duración adicional del valor objetivo del intervalo cuando la estación de carga está consumiendo energía (> 500W):",
    ],
    "meas3_ptarget2_txt": [
        'Nur in Verbindung mit dem Intervall-Zielwert unter "Steuerungs-Einstellungen" relevant.',
        'Only relevant in connection with the interval target value under "Control Settings".',
        'Uniquement pertinent en relation avec la valeur cible de l\'intervalle sous "Paramétrages des commandes".',
        'Sólo es relevante en relación con el valor objetivo del intervalo en "Ajustes de control".',
    ],
    "carfct": [
        "E-Auto Funktion",
        "EV Function",
        "Fonction E-Auto",
        "Función Vehículo Eléctrico",
    ],
    "car_mode": [
        "E-Auto Ladefunktion:",
        "EV Charging:",
        "Fonction charge E-Auto:",
        "Función de carga Vehículo Eléctrico:",
    ],
    "car_mode0": ["Aus", "Off", "Désactivée", "Apagado"],
    "car_mode1": ["Ein", "On", "Activée", "Encendido"],
    "car_state": [
        "Status Ladestation:",
        "Charging station state:",
        "État station de charge:",
        "Estado estación de carga:",
    ],
    "car_ip": [
        "Ladestation IP Adresse:",
        "Charging station IP address:",
        "Adresse IP station de charge:",
        "Dirección IP de la estación de carga:",
    ],
    "car_pthres": [
        "Leistungsschwelle:",
        "Power threshold:",
        "Seuil de puissance:",
        "Umbral de potencia:",
    ],
    "car_int": [
        "Ansteuerungsintervall:",
        "Control interval:",
        "Intervalle de commande:",
        "Intervalo de activación:",
    ],
    "car_imax": [
        "Max. Ladestrom:",
        "Max. charging current:",
        "Courant de charge max.:",
        "Max. corriente de carga:",
    ],
    "car_swtim1": [
        "Zeit Schwellen-Überschreitung:",
        "Time threshold exceeded:",
        "Dépassement du seuil temporel: ",
        "Umbral de tiempo superado:",
    ],
    "car_swtim2": [
        "Min. Zeit ein:",
        "Min. time on:",
        "Temps min. activé: ",
        "Tiempo mínimo activado:",
    ],
    "car_swtim3": [
        "Min. Zeit aus:",
        "Min. time off:",
        "Temps min. désactivé:",
        "Min. tiempo apagado:",
    ],
    "car_ss": [
        "Sicherstellungs-Modus:",
        "Recharging-mode:",
        "Mode sécurisation:",
        "Modo intervalo:",
    ],
    "car_ssmode0": ["Aus", "Off", "Désactivé", "Apagado"],
    "car_ssmode1": ["Ein", "On", "Activé", "Encendido"],
    "car_ssimax": [
        "Sicherstellung Ladestrom:",
        "Recharging current:",
        "Sécurisation courant de charge:",
        "Intervalo corriente de carga:",
    ],
    "car_sstf1": [
        "Sicherstellung Zeitfenster 1 von / bis:",
        "Recharging timeframe 1 from / to:",
        "Créneau horaire sécurisation 1 de / à: ",
        "Intervalo ventana tiempo 1 desde / hasta:",
    ],
    "car_sstf1en": [
        "Sicherstellung Zeitfenster 1 Ladeenergie 1 / 3 ph:",
        "Recharging timeframe 1 charging energy 1 / 3 ph:",
        "Créneau horaire sécurisation 1 énergie de charge 1 / 3 ph:",
        "Intervalo ventana tiempo 1 cargando energía 1 / 3 ph:",
    ],
    "car_sstf2": [
        "Sicherstellung Zeitfenster 2 von / bis:",
        "Recharging timeframe 2 from / to:",
        "Créneau horaire sécurisation 2 de / à: ",
        "Intervalo ventana tiempo 2 desde / hasta:",
    ],
    "car_sstf2en": [
        "Sicherstellung Zeitfenster 2 Ladeenergie 1 / 3 ph:",
        "Recharging timeframe 2 charging energy 1 / 3 ph:",
        "Créneau horaire sécurisation 2 énergie de charge 1 / 3 ph: ",
        "Intervalo ventana tiempo 2 cargando energía 1 / 3 ph:",
    ],
    "car_sswd": [
        "Sicherstellung Wochentage:",
        "Recharging weekday:",
        "Sécurisation jours de la semaine:",
        "Intervalo días de semana:",
    ],
    "multiunits": [
        "Mehrere Geräte",
        "Multi Units",
        "Plusieurs dispositifs",
        "Varios dispositivos",
    ],
    "multiunits_smatxt": [
        "Der Ansteuerungstyp 'SMA Home Manager' unterstützt nicht mehrere Geräte. Allerdings können Sie direkt mit dem SMA Home Manager mehrere my-PV Geräte ansteuern.",
        "The Control Type setting 'SMA Home Manager' does not support multi-unit-mode, but you can control multiple my-PV devices directly using the SMA Home Manager.",
        "Le type de contrôle 'SMA Home Manager' ne prend pas en charge plusieurs dispositifs. Cependant, vous pouvez contrôler plusieurs my-PV appareils directement avec SMA Home Manager.",
        "El tipo de control 'SMA Home Manager' no soporta múltiples dispositivos. Sin embargo, puedes controlar varios my-PV dispositivos directamente con SMA Home Manager.",
    ],
    "multiunits_mode": ["Modus:", "Mode:", "Mode:", "Modo:"],
    "multiunits_mode1": ["Aus", "Off", "Désactivé", "Apagado"],
    "multiunits_mode2": ["Synchron", "Synchron", "Synchrone", "Sincronizado"],
    "multiunits_mode3": ["Schicht", "Stratify", "Strate", "Estratificado"],
    "multiunits_slaves": [
        "Sekundärregler:",
        "Slaves:",
        "Régulateur secondaire:",
        "Esclavos:",
    ],
    "multiunits_slaves1": [
        "Gerät Nr.",
        "Unit No.",
        "N° dispositif ",
        "Dispositivo No.",
    ],
    "multiunits_slaves2": ["Aktiv", "Enable", "Actif", "Activo"],
    "multiunits_state0": [
        "nicht verfügbar",
        "not available",
        "non disponible",
        "No disponible",
    ],
    "multiunits_state1": [
        "Warnung: Mehr als ein Gerät mit dieser Nummer im System",
        "Warning: More than one device with this ID in the system",
        "Attention: Plus d'un dispositif avec ce numéro dans le système",
        "Advertencia: Más de un dispositivo con este número en el sistema",
    ],
    "ipset": ["IP Einstellungen", "IP Settings", "Paramétrage IP", "Ajustes de IP"],
    "ipset_mac": ["MAC Adresse:", "MAC address:", "Adresse MAC:", "Dirección MAC:"],
    "ipset_ip": [
        "Aktuelle IP Adresse:",
        "Current IP address:",
        "Adresse IP actuelle:",
        "Dirección IP actual:",
    ],
    "ipset_sn": [
        "Aktuelle Subnetz Maske:",
        "Current subnet mask:",
        "Masque de sous-réseau actuel:",
        "Máscara de subred actual:",
    ],
    "ipset_gw": [
        "Aktuelles Gateway:",
        "Current gateway:",
        "Gateway actuel:",
        "Gateway actual:",
    ],
    "ipset_dns": ["Aktueller DNS:", "Current DNS:", "DNS actuel:", "DNS actual:"],
    "ipset_ethmode": [
        "Ethernet-Modus:",
        "Ethernet-Mode:",
        "Mode Ethernet:",
        "Modo Ethernet:",
    ],
    "ipset_ethmode_txt": [
        "Eine Änderung des Ethernet-Modus wird erst nach einem Geräteneustart wirksam.",
        "A change of the Ethernet mode becomes effective only after a device restart.",
        "Une modification du mode Ethernet n'est effective qu'après un redémarrage de l'appareil.",
        "El cambio del modo Ethernet sólo se hace efectivo tras un reinicio del dispositivo.",
    ],
    "ipset_wlanpwd_txt": [
        "Eine Änderung der WLAN-Parameter (SSID und Passwort) wird erst nach einem Geräteneustart wirksam.",
        "A change of the WiFi parameters (SSID and password) will only take effect after a device restart.",
        "Une modification des paramètres WiFi (SSID et mot de passe) ne sera effective qu'après un redémarrage de l'appareil.",
        "Un cambio de los parámetros WiFi (SSID y contraseña) sólo tendrá efecto después de un reinicio del dispositivo.",
    ],
    "ipset_ethmode0": ["LAN", "LAN", "LAN", "LAN"],
    "ipset_ethmode1": ["WLAN", "WiFi", "WiFi", "WiFi"],
    "ipset_wlanssid": ["WLAN SSID:", "WiFi SSID:", "WiFi SSID:", "WiFi SSID:"],
    "ipset_wlanpwd": [
        "WLAN Passwort:",
        "WiFi password:",
        "Mot de passe WiFi:",
        "Contraseña WiFi:",
    ],
    "ipset_dhcpmode": ["DHCP-Modus:", "DHCP-Mode:", "Mode DHCP:", "Modo DHCP:"],
    "ipset_dhcpmode_txt": [
        "Statische IP Adressen nur verwenden, wenn Sie mit Netzwerk-Administration vertraut sind.",
        "Use static IP only if you are familiar with network administration.",
        "N'utilisez des adresses IP statiques que si vous êtes familier avec l'administration des réseaux.",
        "Utilice direcciones IP estáticas solo si está familiarizado con la administración de redes.",
    ],
    "ipset_dhcpmode1": ["DHCP", "DHCP", "DHCP", "DHCP"],
    "ipset_dhcpmode2": ["Statische IP", "Static IP", "IP statique", "IP estática"],
    "ipset_sip": ["IP Adresse:", "IP address:", "Adresse IP:", "Dirección IP:"],
    "ipset_ssn": [
        "Subnetz Maske:",
        "Subnet mask:",
        "Masque de sous-réseau:",
        "Máscara de subred:",
    ],
    "ipset_sgw": ["Gateway:", "Gateway:", "Gateway:", "Gateway:"],
    "ipset_sdns": ["DNS Server:", "DNS server:", "Serveur DNS:", "Servidor DNS:"],
    "basset": [
        "Grundeinstellungen",
        "Basic Settings",
        "Paramètres de base",
        "Ajustes básicos",
    ],
    "basset_num": ["Nummer:", "Number:", "Numéro:", "Número:"],
    "basset_fuse": ["Absicherung:", "Fusetype:", "Protection:", "Fusible:"],
    "basset_maxpw": [
        "Max. Leistung:",
        "Max. power:",
        "Puissance max.:",
        "Max. Potencia:",
    ],
    "basset_meter_ct": [
        "CT-Klemme Primärstrom:",
        "CT-clamp primary current:",
        "Courant primaire du CT-clamp:",
        "Corriente primaria del transformador de corriente:",
    ],
    "basset_meter_ct_other_info": [
        "Der maximale Strom der Sekundärwicklung darf 125 mA nicht überschreiten.",
        "Maximal secondary winding current must not exceed 125mA.",
        "Le courant maximal de l'enroulement secondaire ne doit pas dépasser 125 mA.",
        "La corriente máxima del devanado secundario no debe superar los 125mA.",
    ],
    "basset_meter_ct_pri": [
        "CT-Klemmenstrom primär/sekundär:",
        "CT clamp current primary/secondary:",
        "Courant de pincement du TC primaire/secondaire:",
        "Corriente primaria/secundaria del transformador:",
    ],
    "basset_meter_ct_val": [
        "CT-Klemmenverhältnis:",
        "CT clamp ratio:",
        "Rapport de serrage du CT:",
        "Relación del transformador de corriente:",
    ],
    "cloudmode": ["Cloud Modus", "Cloud Mode", "Mode Cloud", "Modo Cloud"],
    "cloudmode_privacy": [
        "Mit der Aktivierung erkläre ich mich einverstanden Gerätedaten an die Onlineplattform my-pv.LIVE zu übermitteln. Diese werden streng vertraulich behandelt und nicht an Dritte weitergegeben. my-PV kann Gerätedaten für interne Zwecke nutzen, wie beispielsweise zur Datenanalyse, Forschung oder zur Verbesserung der Produkte. Nähere Informationen zu den Datenschutzbestimmungen entnehmen sie bitte dem folgenden Link: <a href='https://www.my-pv.com/de/ueber-uns/datenschutzerklaerung' target='_blank'>https://www.my-pv.com/de/ueber-uns/datenschutzerklaerung</a>",
        "With the activation I agree to transmit device data to the online platform my-pv.LIVE. This data will be kept strictly confidential and will not be passed on to third parties. my-PV may use device data for internal purposes such as data analysis, research or product improvement. For more information on privacy policy, please refer to the following link: <a href='https://www.my-pv.com/en/about-us/data-protection-declaration' target='_blank'>https://www.my-pv.com/en/about-us/data-protection-declaration</a>",
        "Avec l'activation, j'accepte de transmettre les données du dispositif à la plateforme en ligne my-pv.LIVE. Ces données sont traitées de manière strictement confidentielle et ne sont pas transmises à des tiers. my-PV peut utiliser les données des dispositifs à des fins internes, telles que l'analyse des données, la recherche ou l'amélioration des produits. Pour plus d'informations sur la réglementation relative à la protection des données, veuillez vous référer au lien suivant: <a href='https://www.my-pv.com/en/about-us/data-protection-declaration' target='_blank'>https://www.my-pv.com/en/about-us/data-protection-declaration</a>",
        "Con la activación me comprometo a transmitir los datos del dispositivo a la plataforma online my-pv.LIVE. Estos datos se tratarán de forma estrictamente confidencial y no se transmitirán a terceros. my-PV puede utilizar los datos del dispositivo para fines internos, como el análisis de datos, la investigación o la mejora de productos. Para obtener más información sobre las normas de protección de datos, consulte el siguiente enlace: <a href='https://www.my-pv.com/en/about-us/data-protection-declaration' target='_blank'>https://www.my-pv.com/en/about-us/data-protection-declaration</a>",
    ],
    "cloudmode1": ["aktiviert", "Enabled", "activé", "activado"],
    "cloudmode2": ["deaktiviert", "Disabled", "désactivé", "desactivado"],
    "debugmode": ["Debug Modus", "Debug Mode", "Mode Debug", "Modo Debug"],
    "debugmode_txt": [
        "Debug-Modus nur in Abstimmung mit my-PV aktivieren.",
        "Enable debug mode only after consulting my-PV.",
        "Activez le mode Debug uniquement en coordination avec my-PV.",
        "Activar el modo Debug sólo en coordinación con my-PV.",
    ],
    "debugmode1": ["aktiviert", "Enabled", "activé", "activado"],
    "debugmode2": ["deaktiviert", "Disabled", "désactivé", "desactivado"],
    "fwvers": [
        "Software Version",
        "Firmware Version",
        "Version du logiciel",
        "Versión software",
    ],
    "fwvers_et": [
        "E/Ethernet Version:",
        "E/Ethernet version:",
        "Version E/Ethernet:",
        "Versión E/Ethernet:",
    ],
    "fwvers_etlatest": ["Neueste:", "Latest:", "La plus récente:", "La más nueva:"],
    "fwvers_etstate": ["Status:", "State:", "État:", "Estado:"],
    "fwvers_etstate_txt1": [
        "Nicht geprüft",
        "Not checked",
        "Non vérifié",
        "No se ha comprobado",
    ],
    "fwvers_etstate_txt2": ["Aktuell", "Up to date", "Actuel", "Actual"],
    "fwvers_etstate_txt3": ["Warte", "Wait", "En attente", "Esperar"],
    "fwvers_etstate_txt4": [
        "Download aktiv - noch fehlende Dateien: ",
        "Downloading - files left: ",
        "Téléchargement actif - fichiers encore manquants: ",
        "Descarga activa - todavía faltan archivos: ",
    ],
    "fwvers_updateerror": [
        "Softwareupdate konnte aufgrund eines Verbindungsfehlers nicht durchgeführt werden!",
        "Last Firmware-Update was canceled because of a connection error!",
        "La mise à jour du logiciel n'a pas pu être effectuée en raison d'une erreur de connexion !",
        "¡La actualización del software no pudo ser ejecutada debido a un error de conexión!",
    ],
    "fwvers_ps": [
        "P/Leistungsteil Version:",
        "P/Power stage version:",
        "Version étage de puissance P:",
        "Etapa de potencia P:",
    ],
    "fwvers_pslatest": ["Neueste:", "Latest:", "La plus récente:", "La más nueva:"],
    "fwvers_psstate": ["Status:", "State:", "État:", "Estado:"],
    "fwvers_psstate_txt1": [
        "Nicht geprüft",
        "Not checked",
        "Non vérifié",
        "No se ha comprobado",
    ],
    "fwvers_psstate_txt2": ["Aktuell", "Latest", "Actuel", "Actual"],
    "fwvers_psstate_txt3": [
        "Wird installiert",
        "Update in progress",
        "Sera installé",
        "Se instalará",
    ],
    "fwvers_p9s": [
        "S/Leistungsteil 9s Version:",
        "S/Power stage 9s version:",
        "Version étage de puissance S:",
        "Etapa de potencia S:",
    ],
    "fwvers_p9slatest": ["Neueste:", "Latest:", "La plus récente:", "La más nueva:"],
    "fwvers_p9sstate": ["Status:", "State:", "État:", "Estado:"],
    "fwvers_p9sstate_txt1": [
        "Nicht geprüft",
        "Not checked",
        "Non vérifié",
        "No se ha comprobado",
    ],
    "fwvers_p9sstate_txt2": ["Aktuell", "Latest", "Actuel", "Actual"],
    "fwvers_p9sstate_txt3": [
        "Wird installiert",
        "Update in progress",
        "Sera installé",
        "Se instalará",
    ],
    "fwvers_meter": [
        "Software Version",
        "Firmware Version",
        "Version du logiciel",
        "Versión software",
    ],
    "fwvers_sn": [
        "Seriennummer:",
        "Serial No:",
        "Numéro de série:",
        "Número de serie:",
    ],
    "fwvers_eximp": [
        "Exportiere & importiere Einstellungen:",
        "Export & import Settings:",
        "Paramètres d'exportation et d'importation:",
        "Configuración de exportación e importación:",
    ],
    "fwvers_eximpinfo": [
        "nur noch über my-PV.LIVE möglich",
        "only possible via my-PV.LIVE",
        "uniquement possible via my-PV.LIVE",
        "sólo es posible a través de my-PV.LIVE",
    ],
    "fwvers_setimp": ["Importieren", "Import", "Importer", "Importar"],
    "message_offline": [
        "Verbindung verloren",
        "Timeout occured",
        "Perte de connexion",
        "Pérdida de conexión",
    ],
    "message_browser_nsupp": [
        "Ihr Browser unterstüzt diese Funktion nicht.",
        "Your browser does not support this feature.",
        "Votre navigateur ne prend pas en charge cette fonction.",
        "Su navegador no soporta esta función.",
    ],
    "confirm_reboot": [
        "Gerät resetieren?",
        "Reboot device?",
        "Réinitialiser le dispositif ?",
        "¿Reiniciar el dispositivo?",
    ],
    "confirm_factreset": [
        "Auf Werkseinstellungen zurücksetzen?",
        "Factory reset?",
        "Rétablir les paramètres d'usine ?",
        "¿Reponer los ajustes de fábrica?",
    ],
    "confirm_fwdownload": [
        "Neue Firmware herunterladen?",
        "Download new firmware?",
        "Télécharger un nouveau firmware ?",
        "¿Descargar un nuevo firmware?",
    ],
    "confirm_fwupdate": [
        "Firmware Update durchführen?",
        "Firmware update?",
        "Effectuer une mise à jour du firmware ?",
        "¿Realizar la actualización del firmware?",
    ],
    "confirm_psfwupdate": [
        "Leistungsteil Firmware herunterladen und installieren?",
        "Download and install power stage firmware?",
        "Télécharger et installer le firmware de l'étage de puissance ?",
        "¿Descargar e instalar el firmware de la unidad de potencia?",
    ],
    "confirm_p9sfwupdate": [
        "S-Leistungsteil Firmware herunterladen und installieren?",
        "Download and install s-power stage firmware?",
        "Télécharger et installer le firmware de l'étage de puissance S ?",
        "¿Descargar e instalar el firmware de la sección de potencia S?",
    ],
    "help_nodevice": [
        "Kein Gerät aktiv.",
        "No device active.",
        "Aucun dispositif actif.",
        "Ningún dispositivo activo.",
    ],
    "wd1": ["Mo", "Mon", "L", "Lu"],
    "wd2": ["Di", "Tue", "Ma", "Ma"],
    "wd3": ["Mi", "Wed", "Me", "Mi"],
    "wd4": ["Do", "Thu", "J", "Ju"],
    "wd5": ["Fr", "Fri", "V", "Vi"],
    "wd6": ["Sa", "Sat", "S", "Sa"],
    "wd7": ["So", "Sun", "D", "Do"],
}
